### ISSUE TITLE
WSSecurity option fails in PasswordText case because nonce is always appended to headers...

### ISSUE THREAD

**Issue by lsalzman** [vpulim/node-soap#123]
When using the PasswordText option of WSSecurity, the WSSecurity.toXML function always appends the &lt;wsse:Nonce&gt; tag. This is causing the remote service over which I have no control to spew errors of the following form:

com.sun.xml.wss.XWSSecurityException: Receiver Requirement for no nonce has not been met, Received token has a nonce specified

Modifying WSSecurity.toXML to only append the nonce in the PasswordDigest case fixes it, like so:

(this._passwordType === 'PasswordText' ?
            '&lt;wsse:Password&gt;'+this._password+'&lt;/wsse:Password&gt;'
            :
            '&lt;wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest" &gt;'+passwordDigest(nonce, created, this._password)+'&lt;/wsse:Password&gt;'
             +
            '&lt;wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" &gt;'+nonce+'&lt;/wsse:Nonce&gt;')

**Comment by fontanon** [comment]
I'm affected too! Please fix!
