### ISSUE TITLE
Not able to use this library on the client side. Getting below errors after importing it.

### ISSUE THREAD

**Issue by virenAhire** [vpulim/node-soap#1262]
I have tried importing it in different ways :

import soap from 'soap';
import {createClient} from 'soap';
import * as soap from 'soap';

None of this seemed to work. Got the below errors.

Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.

Module build failed: UnhandledSchemeError: Reading from "node:events" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.

Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.

**Comment by w666** [comment]
Hi @virenAhire,

Here is the example project, hope this helps.
[example.zip](https://github.com/user-attachments/files/18004945/example.zip)

**Comment by w666** [comment]
@virenAhire did it work for you? 

I assume this is just your code problem, so I am going to close this issue if it stays inactive.

**Comment by hornta** [comment]
> I have tried importing it in different ways :
> 
> import soap from 'soap'; import {createClient} from 'soap'; import * as soap from 'soap';
> 
> None of this seemed to work. Got the below errors.
> 
> Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme). Webpack supports "data:" and "file:" URIs by default.
> 
> Module build failed: UnhandledSchemeError: Reading from "node:events" is not handled by plugins (Unhandled scheme). Webpack supports "data:" and "file:" URIs by default.
> 
> Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme). Webpack supports "data:" and "file:" URIs by default.

It doesn't seemt to be built for usage in the browser which I guess is what you are trying to do. Work will have to be done to not rely on node internals like "crypto", "events" and more.

**Comment by w666** [comment]
Thread is not active, closing.
