### ISSUE TITLE
When trying to use createClientAsync with xml in string format, getting error:  Cannot read properties of undefined (reading 'elements')"

### ISSUE THREAD

**Issue by amankumarlabra** [vpulim/node-soap#1263]
**error:** 
![image](https://github.com/user-attachments/assets/7164aeee-f3ca-4482-ac79-f68619b6a539)

**wsdl file used:** <?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
	xmlns:tns="http://tempuri.org/"
	xmlns:s="http://www.w3.org/2001/XMLSchema"
	xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://tempuri.org/">
	<wsdl:types>
...
</wsdl:types>
	<wsdl:message name="AddSoapIn">
		<wsdl:part name="parameters" element="tns:Add"/>
	</wsdl:message>
	<wsdl:message name="AddSoapOut">
		<wsdl:part name="parameters" element="tns:AddResponse"/>
	</wsdl:message>
	<wsdl:message name="SubtractSoapIn">
		<wsdl:part name="parameters" element="tns:Subtract"/>
	</wsdl:message>
	<wsdl:message name="SubtractSoapOut">
		<wsdl:part name="parameters" element="tns:SubtractResponse"/>
	</wsdl:message>
	<wsdl:message name="MultiplySoapIn">
		<wsdl:part name="parameters" element="tns:Multiply"/>
	</wsdl:message>
	<wsdl:message name="MultiplySoapOut">
		<wsdl:part name="parameters" element="tns:MultiplyResponse"/>
	</wsdl:message>
	<wsdl:message name="DivideSoapIn">
		<wsdl:part name="parameters" element="tns:Divide"/>
	</wsdl:message>
	<wsdl:message name="DivideSoapOut">
		<wsdl:part name="parameters" element="tns:DivideResponse"/>
	</wsdl:message>
	<wsdl:portType name="CalculatorSoap">
		<wsdl:operation name="Add">
			<wsdl:documentation
				xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">Adds two integers. This is a test WebService. ©DNE Online
			
			</wsdl:documentation>
			<wsdl:input message="tns:AddSoapIn"/>
			<wsdl:output message="tns:AddSoapOut"/>
		</wsdl:operation>
		<wsdl:operation name="Subtract">
			<wsdl:input message="tns:SubtractSoapIn"/>
			<wsdl:output message="tns:SubtractSoapOut"/>
		</wsdl:operation>
		<wsdl:operation name="Multiply">
			<wsdl:input message="tns:MultiplySoapIn"/>
			<wsdl:output message="tns:MultiplySoapOut"/>
		</wsdl:operation>
		<wsdl:operation name="Divide">
			<wsdl:input message="tns:DivideSoapIn"/>
			<wsdl:output message="tns:DivideSoapOut"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CalculatorSoap" type="tns:CalculatorSoap">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="Add">
			<soap:operation soapAction="http://tempuri.org/Add" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="Subtract">
			<soap:operation soapAction="http://tempuri.org/Subtract" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="Multiply">
			<soap:operation soapAction="http://tempuri.org/Multiply" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="Divide">
			<soap:operation soapAction="http://tempuri.org/Divide" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:binding name="CalculatorSoap12" type="tns:CalculatorSoap">
		<soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="Add">
			<soap12:operation soapAction="http://tempuri.org/Add" style="document"/>
			<wsdl:input>
				<soap12:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap12:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="Subtract">
			<soap12:operation soapAction="http://tempuri.org/Subtract" style="document"/>
			<wsdl:input>
				<soap12:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap12:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="Multiply">
			<soap12:operation soapAction="http://tempuri.org/Multiply" style="document"/>
			<wsdl:input>
				<soap12:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap12:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="Divide">
			<soap12:operation soapAction="http://tempuri.org/Divide" style="document"/>
			<wsdl:input>
				<soap12:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap12:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="Calculator">
		<wsdl:port name="CalculatorSoap" binding="tns:CalculatorSoap">
			<soap:address location="http://www.dneonline.com/calculator.asmx"/>
		</wsdl:port>
		<wsdl:port name="CalculatorSoap12" binding="tns:CalculatorSoap12">
			<soap12:address location="http://www.dneonline.com/calculator.asmx"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>

**Comment by amankumarlabra** [comment]
wsd file: 
[test.txt](https://github.com/user-attachments/files/18005740/test.txt)

**Comment by amankumarlabra** [comment]
It is working when i use the url of wsdl : http://www.dneonline.com/calculator.asmx?wsdl,
but fails when i give xml in string format

**Comment by w666** [comment]
I will try to have a look tomorrow. It is midnight at my place.

**Comment by w666** [comment]
Coud you please provide a code snippet? That would help to replicate and understand the problem.

**Comment by amankumarlabra** [comment]
**Code Snippet:**
            createClientAsync(xml).then((client) => {
                const args = {intA: '100', intB: '201'};
                const methodName = 'AddAsync';
                return client[methodName](args).then((response: any) => {
                    const data = response[0];
                    return data;
                }).catch((error) => {
                    const {logger} = this.config;
                    logger.error(`Error in userFetch %O`, JSON.stringify(error));
                    return Promise.reject(errorData);
                });
            }).catch((error) => {
                const {logger} = this.config;
                logger.error(`Error in userFetch %O`, JSON.stringify(error));
                return Promise.reject(errorData);
            });

**Comment by w666** [comment]
Your WSDL is not valid. Just copy what is in http://www.[dneonline.com/calculator.asmx?wsdln and it will work.

```javascript
    await createClientAsync('./test.wsdl').then((client) => {
        const args = { intA: '100', intB: '201' };
        const methodName = 'AddAsync';
        return client[methodName](args).then((response) => {
            const data = response[0];
            console.log(`response`, response)
            return data;
        }).catch((error) => {
            const { logger } = this.config;
            logger.error(`Error in userFetch %O`, error);
            return Promise.reject(errorData);
        });
    }).catch((error) => {
        console.error(`Error in userFetch %O`, error);
        throw error;
    });
```
so output is 
```
$ npm run start

> soap-connection-header-test@1.0.0 start
> node index.js

response [
  { AddResult: 301 },
  '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><AddResponse xmlns="http://tempuri.org/"><AddResult>301</AddResult></AddResponse></soap:Body></soap:Envelope>',
  undefined,
  '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:tns="http://tempuri.org/"><soap:Body><Add xmlns="http://tempuri.org/"><intA>100</intA><intB>201</intB></Add></soap:Body></soap:Envelope>',
  undefined
]
```

I am sorry but not a position to debug your code. Please take time and try do it your self.

Closin issue.
