### ISSUE TITLE
Multiple Import Schemas and Namespaces

### ISSUE THREAD

**Issue by sataylor7** [vpulim/node-soap#204]
I have seen the issue 163 thats close to what my issue is, but I am having issues with multiple namespaces.

This is the WSDL
http://ultra-api.ultradns.com/UltraDNS_WS/v01?wsdl

When node-soap goes through to make the client, it fails when it tries to create a method that exist in another schema.

(I took off the front part so that it would show)
message name="getResourceRecordsOfDNameByTypeResponse">
part name="ResourceRecordList" type="ns1:ResourceRecordList">
part>
message>

It needs to look at this (I took out the beginning part)
 xmlns:ns1="http://webservice.api.ultra.neustar.com/v01/" xmlns:ns2="http://schema.ultraservice.neustar.com/" xmlns:tns="http://schema.ultraservice.neustar.com/v01/" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://schema.ultraservice.neustar.com/v01/" 

P.S. I tried to switch the ns1 and ns2 on my local WSDL and that did not make a difference.

I have debugged the WSDL.js, but I have not found where to add a clause to look for more than one namespace.

**Comment by forAKhaliq** [comment]
Hi
@devotis @jsdevel  I am having similar issue I am creating soap server, I am wsdl file contains multiple spaces, while generating response of a web service method, all elements contains only single name space, however for each element there is different namespace defined in wsdl file
