### ISSUE TITLE
Empty element of type xsd:string results in empty object instead of empty string

### ISSUE THREAD

**Issue by kreutter** [vpulim/node-soap#213]
I get a SOAP response looking like this:

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <soap:Body>
      <!-- … -->
         <AccountData>
            <!-- … --->
            <Name></Name>
            <!-- … --->
      </AccountData >
      <!-- … -->
   </soap:Body>
</soap:Envelope>
```

and here is the definition of the reply from the WSDL:

```
<s:complexType name="AccountData">
  <s:sequence>
    <!-- … -->
    <s:element minOccurs="1" maxOccurs="1" name="Name" type="s:string" />
    <!-- … -->
  </s:sequence>
</s:complexType>
```

When `<Name>` is not empty I get a String in the resulting JavaScript object but when `<Name>` is empty I don't get an empty string as I would expect but an empty object ({}). Or in other words:
- `<Name>Foo</Name>` => `'Foo'`
- `<Name></Name>` => `{}` **expected**: `''` (empty string since type is `xsd:string`)

Is this intended behavior?

**Comment by vincic** [comment]
Any status update on this? Still in 0.6.1

**Comment by herom** [comment]
Unfortunately there is no update on this issue @vincic - I'm sorry.

**Comment by spock123** [comment]
I'm having the same issue.
I wonder if we could use a 3rd party xmlToJson module to do the parsing?

**Comment by herom** [comment]
@spock123 do you have some specific module in mind? Right now, we're using the `sax` library for parsing XML - are there better alternatives out there in the npm universe?

**Comment by spock123** [comment]
@herom not as I seed.. I've been looking into the code a little bit and found about about Sax... 

So far I've ended up "parsing" the returned Json and replacing empty objects with empty strings, for the values I know are supposed to be strings. But this is not a good solution, would be awesome if we somehow to solve this. But as I see it, it's somewhere in the Sax module

**Comment by vincic** [comment]
I made one solution in commit https://github.com/vincic/node-soap/commit/421a9ba1b1149d5c8419bb3f882943853a9e909d but I had  problems creating a proper test. I tried with the request-response-samples way but my element always had undefined schema so my fix didn't work in the test.

Beside a missing test I am only worrying about the performance penalty for this fix, comments are welcome. 

Anyway the fix breaks three tests. From what I can see, they should be changed since the expected value should be empty string and not an empty object.

  2) Request Response Sampling Messages suffixed with In Out:

 ```     
Uncaught AssertionError: "{\"return\":\"-1\",\"bstrError\":\"\"}" == "{\"return\":\"-1\",\"bstrError\":{}}"
      + expected - actual

      +{"return":"-1","bstrError":{}}
      -{"return":"-1","bstrError":""}
  ```  
     
  3) Request Response Sampling Messages suffixed with Input Output:

  ```
    Uncaught AssertionError: "{\"return\":\"-1\",\"bstrError\":\"\"}" == "{\"return\":\"-1\",\"bstrError\":{}}"
      + expected - actual

      +{"return":"-1","bstrError":{}}
      -{"return":"-1","bstrError":""}
```      
   
  4) Request Response Sampling Messages suffixed with Request Response:

```
      Uncaught AssertionError: "{\"return\":\"-1\",\"bstrError\":\"\"}" == "{\"return\":\"-1\",\"bstrError\":{}}"
      + expected - actual

      +{"return":"-1","bstrError":{}}
      -{"return":"-1","bstrError":""}
```

**Comment by vincic** [comment]
All tests passes now and the fix works for our production. Anyone looked at the pull request?

**Comment by shine-on** [comment]
@vincic, could you provide a link to pull request you are referring to?

**Comment by simonjosefsson** [comment]
@shine-on 
#637 is referenced above his comment

**Comment by vincic** [comment]
@shine-on any feedback on the #637 pull request?
