### ISSUE TITLE
ETIMEDOUT when reading wsdl from url

### ISSUE THREAD

**Issue by imavroukakis** [vpulim/node-soap#235]
I'm trying to construct a client from the WSDL url, which looks like this:

http://somehost:8080/TA/TAService.svc?wsdl (windows backed server). The wsdl has the usual schema locations

```
<xsd:import schemaLocation="http://somehost:8080/TA/TAService.svc?xsd=xsd1" namespace="http://www.me.com/ns/2012/01/01/webservices/TAService_1/"/>
<xsd:import schemaLocation="http://somehost:8080/TA/TAService.svc?xsd=xsd3" namespace="http://schemas.me.com/ns/2005/08/infrastructure/tornado_soap"/>
<xsd:import schemaLocation="http://somehost:8080/TA/TAService.svc?xsd=xsd0" namespace="http://schemas.microsoft.com/2003/10/Serialization/"/>
<xsd:import schemaLocation="http://somehost:8080/TA/TAService.svc?xsd=xsd2" namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
```

The client fails to be constructed with
`{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }`

But perversely, if I download the WSDL and provide it as a file path then I can get a client created successfully AND perform a call.

Any ideas as to what might be causing this?

**Comment by paambaati** [comment]
Just wanted to know if there is a fix or a workaround for this issue.

**Comment by felipecm** [comment]
+1
