### ISSUE TITLE
Namespace problems

### ISSUE THREAD

**Issue by O9F9** [vpulim/node-soap#426]
Hi,

For some reason my request isn't formatted properly.

This is what the soap module produces, but the server fails to read the arguments:

``` xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:tns="http://ws.myservice.com/">
<soap:Header>
</soap:Header>
<soap:Body>


<registerChallengePassword xmlns:tns="http://ws.myservice.com/" xmlns="http://ws.myservice.com/">
<arg0>abcd1234</arg0><arg1>efgh5678</arg1>
</registerChallengePassword>


</soap:Body>
</soap:Envelope>
```

This is an example of a working request. Notice that the "registerChallengePassword" has the "tns" prefix:

``` xml
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns:tns="http://ws.myservice.com/">
<soap:Header>
</soap:Header>
<soap:Body>


<tns:registerChallengePassword xmlns:tns="http://ws.myservice.com/">
<arg0>abcd1234</arg0><arg1>efgh5678</arg1>
</tns:registerChallengePassword>


</soap:Body>
</soap:Envelope>
```

I was able to get the soap module to produce this by modifying wsdl.js. Could this be a bug, or is there some special option I should be using when initialzing my client..?

WSDL for reference:

``` xml
<definitions name='WebServices'
targetNamespace='http://ws.myservice.com/'
xmlns='http://schemas.xmlsoap.org/wsdl/'
xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
xmlns:tns='http://ws.myservice.com/'
xmlns:xsd='http://www.w3.org/2001/XMLSchema'>

 <types>
  <xs:schema targetNamespace='http://ws.myservice.com/' version='1.0' xmlns:tns='http://ws.myservice.com/' xmlns:xs='http://www.w3.org/2001/XMLSchema'>
   <xs:element name='registerChallengePassword' type='tns:registerChallengePassword'/>
   <xs:element name='registerChallengePasswordResponse' type='tns:registerChallengePasswordResponse'/>
   <xs:complexType name='registerChallengePassword'>
    <xs:sequence>
     <xs:element minOccurs='0' name='arg0' type='xs:string'/>
     <xs:element minOccurs='0' name='arg1' type='xs:string'/>
    </xs:sequence>
   </xs:complexType>
   <xs:complexType name='registerChallengePasswordResponse'>
    <xs:sequence>
     <xs:element minOccurs='0' name='return' type='xs:string'/>
    </xs:sequence>
   </xs:complexType>
  </xs:schema>
 </types>
 <message name='WebServices_registerChallengePasswordResponse'>
  <part element='tns:registerChallengePasswordResponse' name='registerChallengePasswordResponse'></part>
 </message>
 <message name='WebServices_registerChallengePassword'>
  <part element='tns:registerChallengePassword' name='registerChallengePassword'></part>
 </message>
 <portType name='WebServices'>
  <operation name='registerChallengePassword' parameterOrder='registerChallengePassword'>
   <input message='tns:WebServices_registerChallengePassword'></input>
   <output message='tns:WebServices_registerChallengePasswordResponse'></output>
  </operation>
 </portType>
 <binding name='WebServicesBinding' type='tns:WebServices'>
  <soap:binding style='document' transport='http://schemas.xmlsoap.org/soap/http'/>
  <operation name='registerChallengePassword'>
   <soap:operation soapAction=''/>
   <input>
    <soap:body use='literal'/>
   </input>
   <output>
    <soap:body use='literal'/>
   </output>
  </operation>
 </binding>
 <service name='WebServices'>
  <port binding='tns:WebServicesBinding' name='WebServicesPort'>
   <soap:address location='https://myservice.com/services'/>
  </port>
 </service>
</definitions>
```

**Comment by Ran-P** [comment]
Hey, I have the same problem.

the code:
var soap = require('soap');
var url = 'https://api.bronto.com/v4?wsdl';

var options = {
    ignoredNamespaces: {
        namespaces: ['namespaceToIgnore', 'someOtherNamespace'],
        override: true
    }
}

soap.createClient(url,options, function(err, client) {
    if(err)
    {
        console.log('error in creating client');
        console.error(err);
        return;
    }
  //  console.log(JSON.stringify(client.describe()));
    client.BrontoSoapApiImplService.BrontoSoapApiImplPort.login({apiToken:'XXXXXXXXXXXXXXXXXXXXXXXXXX'}, function(err, result) {
        if(err)
        {
            console.log('error in login');
            console.error(err);
            console.log(client.lastRequest);
            return;
        }
        console.log(result);
    });
});

This is what the soap module produces:
<soap:Envelope 
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
    xmlns:tns="http://api.bronto.com/v4">
    <soap:Body>
        <login>
            <apiToken>XXXXXXXXXXXXXXXXXXXXXXXXXX</apiToken>
        </login>
    </soap:Body>
</soap:Envelope>

instead of:
<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:tns="http://api.bronto.com/v4">
    <soap:Body>
        <tns:login>
            <apiToken>XXXXXXXXXXXXXXXXXXXXXXXXXX</apiToken>
        </tns:login>
    </soap:Body>
</soap:Envelope>

**Comment by Ran-P** [comment]
Changing line 1047 to:
```
WSDL.prototype.ignoredNamespaces = ['targetNamespace', 'typedNamespace'];
```
fix the problem

**Comment by herom** [comment]
Seems related to #537
