### ISSUE TITLE
Request to a service with self signed SSL certificate

### ISSUE THREAD

**Issue by franza** [vpulim/node-soap#459]
I'm trying to create a client to SOAP service that runs over HTTPS using self-signed SSL certificate:

``` javascript
var soap = require('soap');
var url = 'https://example.com/wsdl/Service.wsdl';

soap.createClient(url, function (err, client) {
  if (err) {
    return console.log(err.message);
  }
  console.log(client.describe());
});
```

However I get error: `[Error: DEPTH_ZERO_SELF_SIGNED_CERT]`. Is there some kind of option to avoid this behavior?

**Comment by tesfel** [comment]
Add the cert to your trusted list at you computer or add

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"

to your code.

**Comment by brmarick** [comment]
I realize this is a bit of an old post, however I recently had this problem. While @tesfel suggestion is nice, it opens __vulnerabilities__. I was able to solve this problem via adding the certificates or certificate chain used on the soap server. In particular, I had to add the certificates in two locations, creating the client and the setting the security. 

### createClient
It took some digging, but I found the process to validate a server certificate or use a self-signed certificate on a server. To do this simply make use  of the 'options' parameter for createClient. To set the certificate(s) used by the server set the 'wsdl_options.ca' element. This element takes in an array of Base 64 certificates. Here is an example of how to complete this: 

```javascript
var cert = ['-----BEGIN CERTIFICATE-----\n....--END CERTIFICATE-----'];
var list_cert = [ '-----BEGIN CERTIFICATE-----\n....--END CERTIFICATE-----', ..., '-----BEGIN CERTIFICATE-----\n....--END CERTIFICATE-----'];

var options = {
    wsdl_options: {
        ca: cert,
    },
};
soap.createClient(soap_wsdl, options, function(error, client) {
    if(error) {
        console.log(error)
        return
    }
    client.MyFunction(args, function(err, result) {
        console.log(result);
    });
});
```

### setSecurity
Additionally, you can also run into the self-signed certificate error if you are using an authentication format. Again the solution is to set the ca property in the options parameter of the different security objects. Here is an example for BasicAuthSecurity.

```javascript
securitySettings = { ca: ['-----BEGIN CERTIFICATE-----\n....--END CERTIFICATE-----'] };
client.setSecurity(new soap.BasicAuthSecurity(username, password, securitySettings));
```

I will try to work up a documentation pull request to help document this process.

**Comment by jsdevel** [comment]
please do @brmarick !

**Comment by misland** [comment]
> Add the cert to your trusted list at you computer or add
> 
> process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"
> 
> to your code.

@WerVbn bro, i just want to say, you are such a genius🤩
this work totally well
