### ISSUE TITLE
wsdl parsing does not handle message elements with more than one part

### ISSUE THREAD

**Issue by howardengelhart** [vpulim/node-soap#467]
In the code snippet below, it looks like when the wsdl Message elements are processed, they do not account for  the possibility of a message containing more than one part.

```
MessageElement.prototype.postProcess = function(definitions) {
  var part = null;
  var child;
  var children = this.children || [];
  var ns;
  var nsName;
  var i;
  var type;

  for (i in children) {
    if ((child = children[i]).name === 'part') {
      part = child;
      break;
    }
  }

  if (!part) {
    return;
  }
```

All of the wsdls used by your tests that I inspected seemed to have messages with a single part.. typically pointing towards request/response elements that hold the actual parameters.. DummyRequest.. DummyField1..

However, I believe its valid for WSDL message elements to hold more than one part.  An example snipped from a wsdl I am working with:

```
    <message name='WSWebsiteAdmin_getWebsiteById_Request_Soap'>
        <part name='id' element='ns0:id'/>
        <part name='col' element='ns0:col'/>
    </message>
```

I am looking at putting together a possible fix for this in my own fork of your library, which I'd be happy to contribute back to the community.  That said, given the complexity of your code base, if you could provide some guidance towards the right approach for a fix that would fit in as seamlessly as possible, it would be appreciated.

Thanks,
-h

**Comment by devongovett** [comment]
@howardengelhart did you ever work on this anywhere? This is causing errors with [Sabre's wsdl](http://wsdl-crt.cert.sabre.com/sabreXML1.0.00/usg/SessionCreateRQ.wsdl) as well.

**Comment by howardengelhart** [comment]
Fortunately for us, it became a non-issue when our partner updated their WSDL.   I didn't get too far into looking into addressing the issue, but it seemed like it would take some significant surgery.  Good luck!
