### ISSUE TITLE
Security/Authentication handling is weird

### ISSUE THREAD

**Issue by FrankyBoy** [vpulim/node-soap#469]
I have the case of NTLM authentication (yay, right? :P). Even when using basic auth (which I hoped would work as a fallback), I get a 401 with a WWW-Authenticate header. So I started digging through the code. First reading the code from the provided BasicAuthSecurity, then reading how request.js likes to have it: https://github.com/mikeal/request#http-authentication
Turns out request.js already has (seemingly) way sophisticated authentication capabilities but they go unused and instead special headers are injected.

EDIT: I just saw addOptions, I'll try porting the BasicAuthSecurity to using that instead of addHeaders (which is not documented btw) and see where I'll get.

**Comment by bboydGensler** [comment]
@FrankyBoy did you find a solution for this that can be shared with the community?

**Comment by FrankyBoy** [comment]
nope, sorry, just fell back to request-ntlm (because ntlm is what I needed) and extended that a little bit -> [request-ntlm-continued](https://www.npmjs.com/package/request-ntlm-continued)

**Comment by bboydGensler** [comment]
@FrankyBoy thanks
