### ISSUE TITLE
Procedure 'xxxxxxxxxx' not present

### ISSUE THREAD

**Issue by icaliman** [vpulim/node-soap#476]
Hi!

I get this error after I updated service wsdl:

``` xml
[Error: Invalid response: 500
Body: <?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Body>
    <SOAP-ENV:Fault>
      <faultcode>SOAP-ENV:Server</faultcode>
      <faultstring>Procedure 'DoGetItemsListRequest' not present</faultstring>
    </SOAP-ENV:Fault>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>]
```

You can see the service wsdl here: https://webapi.allegro.pl/service.php?wsdl

Procedure `DoGetItemsListRequest` is present in wsdl, so what is the problem? 
Please save my day! :)

Thanks!

**Comment by KEFIR4UK** [comment]
Hello I have some problem with Allegro Api. If Anyone would help it will be great! I have error -**" Function ("doShowCat") is not a valid method for this service"**. I replaced doShowCat in method `	

    public function ShowCat($Options) {
		$this->checkConnection();
		return $this->_client->doShowCat(
			$this->_session['session-handle-part'],
			$Options['cat-id'],
			$Options['cat-item-state'],
			$Options['cat-item-option'],
			$Options['cat-item-duration-option'],
			$Options['cat-attrib-fields'],
			$Options['cat-sort-options'],
			$Options['cat-items-price'],
			$Options['cat-items-offset'],
			$Options['cat-items-limit']
		);` 
on  doGetItemsList  - 

    	public function ShowCat($Options) {
		$this->checkConnection();
			$dogetitemslist_request = array(
			'webapiKey' => '****',
			'countryId' => 1,
			'filterOptions' => array(
				array(
					'filterId' => 'category',
					'filterValueId' => $Options['cat-id'])),
		);
		return $this->_client->doGetItemsList($dogetitemslist_request);
    
but then I got - **("doGetItemsList") is not a valid method for this service**. I also replaced wsdl from http://webapi.allegro.pl/uploader.php?wsdl on http://webapi.allegro.pl/serice.php?wsdl. After this I got another error **{https://webapi.allegro.pl/service.php}DoQuerySysStatusRequest': Missing child element(s). Expected is ( {https://webapi.allegro.pl/service.php}sysvar ).** Where is the problem?

**Comment by KEFIR4UK** [comment]
I resoved this problem: in my class I change method QuerySysStatus on this:

    public function QuerySysStatus($Component) {
		return $this->_client->doQuerySysStatus(array(
			'sysvar'=>$Component,
			'countryId'=>self::COUNTRY_CODE,
			'webapiKey'=>$this->_config['allegro_key']
		));
	}

but when I got to page - I got white screen, in chrome console wrote - 500 internal server error. I can't figure out what I doing wrong.
