### ISSUE TITLE
AssertionError: invalid message definition for document style binding

### ISSUE THREAD

**Issue by ghost** [vpulim/node-soap#516]
I'm having an issue with a third-party WSDL which unfortunately I am unable to provide in its entirety for confidentiality reasons. Actually the client provides two different flavours of WSDL depending on the version of their software. Both use document literal. One of these WSDL types works fine with node-soap, but the other does not. Here's a fragment from the one that works:

``` xml
<binding name="VHCMobileIFBinding" type="wsdlns:VHCMobileIFInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="GetVersion">
        <soap:operation style="document" soapAction="urn:kcml-VHCMobile:VHCMobileIF#GetVersion"/>
        <input>
            <soap:body use="literal"/>
        </input>
        <output>
            <soap:body use="literal"/>
        </output>
    </operation>
</binding>
```

And here's a fragment from the one that does not work:

``` xml
<binding name="VHCMobileBinding" type="tns:VHCMobilePortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="GetVersion">
        <soap:operation style="document" soapAction="urn:kcml-VHCMobile#GetVersion"/>
        <input>
            <soap:body use="literal" namespace="urn:kcml-VHCMobile"/>
        </input>
        <output>
            <soap:body use="literal" namespace="urn:kcml-VHCMobile"/>
        </output>
    </operation>
</binding>
```

Apart from some namespacing, a key difference is that the one that does not work does not specify a style attribute for soap:binding. Is it possible that this is causing the "AssertionError: invalid message definition for document style binding" when invoking the method?

I am assuming that the default style for SOAP is 'document' nowadays. Third party tools that I have tried e.g. soapUI cope perfectly well with both WSDL types, it's just node-soap that doesn't work. It won't be possible to get the WSDL changed unfortunately.

**Comment by cndgjason** [comment]
I came across the same problem(invalid message definition for document style binding). The solution above can solve it.Thank you @steve-p-com.
