### ISSUE TITLE
BinarySecurityToken

### ISSUE THREAD

**Issue by zbessler** [vpulim/node-soap#525]
Are you planning on adding support for X509 cert to add BinarySecurityToken as an option over username/pass?

I have an enterprise endpoint that we currently use that has this as a requirement.

**Comment by zbessler** [comment]
Nothing on the Roadmap for this?  :(

**Comment by herom** [comment]
@zbessler Sorry for not responding - I completely overlooked this issue, my bad :disappointed: 

`node-soap` gets better and improved by it's many contributors (like you?) who are willing to contribute back to the library. It would be awesome if you could spend some time and implement this feature by [Submitting a Pull Request](https://github.com/vpulim/node-soap/blob/master/CONTRIBUTING.md#submitting-a-pull-request) - I'll be more than happy to merge it :+1:
