### ISSUE TITLE
Not importing functions

### ISSUE THREAD

**Issue by jstans** [vpulim/node-soap#540]
Firstly, apologies for my lack of SOAP knowledge in general.

I'm having a problem where node-soap is not seeing the functions from a wsdl document. I don't know if I'm doing something wrong myself or node-soap is having trouble with the complex looking imports (from my perspective).

The wsdl in question:
https://qa-api.ukmail.com/Services/UKMAuthenticationServices/UKMAuthenticationService.svc?wsdl

Any help with this would be greatly appreciated, as I'm keen to get a better understanding of soap and move on with development.

**Comment by herom** [comment]
What's the particular error you receive? (`node-soap` seems to be able to parse the WSDL (just did a quick test with the URL in question)).

**Comment by dack** [comment]
I'm having the same issue. The WSDL I'm seeing this with is not publicly accessible, but I do see the issue with the WSDL jstans posted as well. Running client.describe on jstans' WSDL results in this:
```
{ UKMAuthenticationService: {} }
```
The WSDL specifies a port named "BasicHttpEndpoint_IUKMAuthenticationService" but the client does not see it.

**Comment by richdunajewski** [comment]
I was seeing this as well with WSDLs from Dalet (not available publicly). It seems when a port is used, the methods defined in the WSDL are not being discovered. In my case, these WSDL's have an `<wsdl:import>` tag, which may also be a factor.

Using the `foam` module on NPM works with the API, but I had to make modifications for SOAP 1.2.
