### ISSUE TITLE
wsdl callback passing string, not Error, in error callback

### ISSUE THREAD

**Issue by dlopuch** [vpulim/node-soap#543]
https://github.com/vpulim/node-soap/blob/v0.6.0/lib/wsdl.js#L976

That line should just pass the full Error instance, not the message string.  

When that error triggers, it eventually gets passed onto consumer code.  It's bad node practice to make error callback params anything other than Error instances (it can break a lot of logging code, for example anything that depends on `errorInstance.stack`).  Not to mention that by passing just the string, you lose the stack that could help you debug.

**Comment by herom** [comment]
@dlopuch thanks a lot for raising this issue (sorry for the long response delay!) - we're up for PRs at any time :smiley:
