### ISSUE TITLE
How to send args to method?

### ISSUE THREAD

**Issue by kevbaker** [vpulim/node-soap#548]
I am attempting to send arguments to a method on this SOAP API. I am getting an error. It seems like I might be formatting the request incorrectly.

### Describe

The "describe" method for the service shows

```javascript

    var url = 'https://www.floristone.com/webservices4/flowershop.cfc?wsdl';

    soap.createClient(url, function(err, client) {
      var clientDescribe = client.describe();

      console.log("client describe:");
      console.log(clientDescribe);
    });

  // =>

  getProducts2013: 
   { input: 
      { APIKey: 'xsd:string',
        APIPassword: 'xsd:string',
        category: 'xsd:string',
        numProducts: 'xsd:double',
        startAt: 'xsd:double' },
```

### Below is my code:

Based on the above I assume I should be using the "input" object keys for my arguments. Does this make sense? 

```javascript
var soap = require('soap');
var url = 'https://www.floristone.com/webservices4/flowershop.cfc?wsdl';
var args = {APIKey:"key123abc", APIPassword:"pwd123abc", category:"aaz", numProducts:10, startAt:0};

soap.createClient(url, function(err, client) {
  client.getProducts2013(args, function(err,result){
    if(!err){
      console.log("Result:")
      console.log(result);
      return result.products;
    }
    else {
      console.log("Error:")
      console.log(err);
    }

  });
});

// ==> { [TypeError: Cannot read property 'Body' of undefined]...}
```

The documentation for the service shows this method `getProducts2013(apiKey, apiPassword, category, numProducts, startAt)`. Does it still make sense for me to format my args the way I have above. I'm getting the above "Body" error.

**Comment by kevbaker** [comment]
Found it. I was using a "startAt" of zero rather than one. A restriction of the SOAP API I'm using without good error handling. Great library. Thanks

**Comment by matthewcanty** [comment]
Hi @kevbaker, do you think a similar thing might be happening to me here: http://stackoverflow.com/questions/28399266/typeerror-when-trying-to-call-national-rail-soap-api-via-node

Can't figure out what is wrong based on the error - not even if it is client or server side.
