### ISSUE TITLE
wsdl parsing bug(?)

### ISSUE THREAD

**Issue by simonjosefsson** [vpulim/node-soap#552]
Hello, first I want to thank @vpulim and all contributors for this module.
I found it really great to work with but alas there seems to be a bug with parsing my wsdl definition.

The wsdl file defines a type ArrayOfString which is later used in getPayrollFile:

    <WSDL:definitions xmlns:MIME="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:SOAP="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mtp="urn:Payroll" xmlns:DIME="http://schemas.xmlsoap.org/ws/2002/04/dime/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="urn:Payroll" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:Payroll" xmlns:WSDL="http://schemas.xmlsoap.org/wsdl/">
      <WSDL:types>
        <xsd:schema xmlns:mtp="urn:Payroll" xmlns="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="urn:Payroll">
          <xsd:import schemaLocation="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://schemas.xmlsoap.org/soap/encoding/" />
          <xsd:complexType name="ArrayOfString">
            <xsd:sequence>
              <xsd:element minOccurs="0" maxOccurs="unbounded" name="string" nillable="true" type="xsd:string" />
            </xsd:sequence>
          </xsd:complexType>
    ....
          <xsd:element name="getPayrollFile">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element minOccurs="0" maxOccurs="1" name="session" nillable="true" type="xsd:string" />
                <xsd:element minOccurs="0" maxOccurs="1" name="month" nillable="true" type="xsd:string" />
                <xsd:element minOccurs="0" maxOccurs="1" name="getPayrollFileUsers" nillable="true" type="tns:ArrayOfString" />
              </xsd:sequence>
            </xsd:complexType>
          </xsd:element>

I used SoapUI to import the wsdl file and test the API, a wireshark capture shows this envelope:

    <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	   <soap:Body>
		  <getPayrollFile xmlns="urn:Payroll">
			 <session>abc123</session>
			 <month>2014-08</month>
			 <getPayrollFileUsers>
				<string>3</string>
				<string>5</string>
			 </getPayrollFileUsers>
		  </getPayrollFile>
	   </soap:Body>
	</soap:Envelope>

However, doing the same API call in Node gives me this:

	<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:mtp="urn:Payroll" xmlns:tns="urn:Payroll" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	   <soap:Body>
		  <tns:getPayrollFile xmlns="urn:Payroll">
			 <tns:session>abc123</tns:session>
			 <tns:month>2014-08</tns:month>
			 <tns:getPayrollFileUsers>3</tns:getPayrollFileUsers>
			 <tns:getPayrollFileUsers>5</tns:getPayrollFileUsers>
		  </tns:getPayrollFile>
	   </soap:Body>
	</soap:Envelope>

As you can see the `getPayrollFileUsers` are not nested into `<string>` tags and so the server ignores them.
I'll try to debug this issue myself but I have limited XML knowledge, any help would be really appreciated

**Comment by simonjosefsson** [comment]
I have some more information after trying to debug this
Below is a snippet from the `schema` variable when in `WSDL.prototype.objextToXML`

ArrayOfString seems fine, but in `getPayrollFile.$lookupTypes` there are only definitions for `session` and `month`. The missing `getPayrollFileUsers` should be there right?

Can someone with a litte XML/SOAP knowledge confirm this? thanks! 

    {
    "nsName":"xsd:schema",
    "namespace":"xsd",
    "name":"schema",
    "children":[
  
    ],
    "xmlns":{
      "mtp":"urn:Payroll",
      "xmlns":"http://www.w3.org/2001/XMLSchema"
    },
    "valueKey":"$value",
    "xmlKey":"$xml",
    "ignoredNamespaces":[
      "tns",
      "targetNamespace",
      "typedNamespace"
    ],
    "$attributeFormDefault":"qualified",
    "$elementFormDefault":"qualified",
    "$targetNamespace":"urn:Payroll",
    "complexTypes":{
      [...]
      "ArrayOfString":{
        "nsName":"xsd:complexType",
        "namespace":"xsd",
        "name":"complexType",
        "children":[
          {
            "nsName":"xsd:sequence",
            "namespace":"xsd",
            "name":"sequence",
            "children":[
              {
                "nsName":"xsd:element",
                "namespace":"xsd",
                "name":"element",
                "children":[
  
                ],
                "xmlns":{
  
                },
                "valueKey":"$value",
                "xmlKey":"$xml",
                "ignoredNamespaces":[
                  "tns",
                  "targetNamespace",
                  "typedNamespace"
                ],
                "$minOccurs":"0",
                "$maxOccurs":"unbounded",
                "$name":"string",
                "$nillable":"true",
                "$type":"xsd:string"
              }
            ],
            "xmlns":{
  
            },
            "valueKey":"$value",
            "xmlKey":"$xml",
            "ignoredNamespaces":[
              "tns",
              "targetNamespace",
              "typedNamespace"
            ]
          }
        ],
        "xmlns":{
  
        },
        "valueKey":"$value",
        "xmlKey":"$xml",
        "ignoredNamespaces":[
          "tns",
          "targetNamespace",
          "typedNamespace"
        ],
        "$name":"ArrayOfString"
      },
      [...]
    },
    
    "elements":{
      [...]
      },
      "getPayrollFile":{
        "nsName":"xsd:element",
        "namespace":"xsd",
        "name":"element",
        "children":[
          {
            "nsName":"xsd:complexType",
            "namespace":"xsd",
            "name":"complexType",
            "children":[
              {
                "nsName":"xsd:sequence",
                "namespace":"xsd",
                "name":"sequence",
                "children":[
                  {
                    "nsName":"xsd:element",
                    "namespace":"xsd",
                    "name":"element",
                    "children":[
  
                    ],
                    "xmlns":{
  
                    },
                    "valueKey":"$value",
                    "xmlKey":"$xml",
                    "ignoredNamespaces":[
                      "tns",
                      "targetNamespace",
                      "typedNamespace"
                    ],
                    "$minOccurs":"0",
                    "$maxOccurs":"1",
                    "$name":"session",
                    "$nillable":"true",
                    "$type":"xsd:string"
                  },
                  {
                    "nsName":"xsd:element",
                    "namespace":"xsd",
                    "name":"element",
                    "children":[
  
                    ],
                    "xmlns":{
  
                    },
                    "valueKey":"$value",
                    "xmlKey":"$xml",
                    "ignoredNamespaces":[
                      "tns",
                      "targetNamespace",
                      "typedNamespace"
                    ],
                    "$minOccurs":"0",
                    "$maxOccurs":"1",
                    "$name":"month",
                    "$nillable":"true",
                    "$type":"xsd:string"
                  },
                  {
                    "nsName":"xsd:element",
                    "namespace":"xsd",
                    "name":"element",
                    "children":[
  
                    ],
                    "xmlns":{
  
                    },
                    "valueKey":"$value",
                    "xmlKey":"$xml",
                    "ignoredNamespaces":[
                      "tns",
                      "targetNamespace",
                      "typedNamespace"
                    ],
                    "$minOccurs":"0",
                    "$maxOccurs":"1",
                    "$name":"getPayrollFileUsers",
                    "$nillable":"true",
                    "$type":"tns:ArrayOfString"
                  }
                ],
                "xmlns":{
  
                },
                "valueKey":"$value",
                "xmlKey":"$xml",
                "ignoredNamespaces":[
                  "tns",
                  "targetNamespace",
                  "typedNamespace"
                ]
              }
            ],
            "xmlns":{
  
            },
            "valueKey":"$value",
            "xmlKey":"$xml",
            "ignoredNamespaces":[
              "tns",
              "targetNamespace",
              "typedNamespace"
            ]
          }
        ],
        "xmlns":{
  
        },
        "valueKey":"$value",
        "xmlKey":"$xml",
        "ignoredNamespaces":[
          "tns",
          "targetNamespace",
          "typedNamespace"
        ],
        "$name":"getPayrollFile",
        "targetNSAlias":"tns",
        "targetNamespace":"urn:Payroll",
        "$lookupType":"parameters",
        "$lookupTypes":[
          {
            "$type":"xsd:string",
            "$name":"session"
          },
          {
            "$type":"xsd:string",
            "$name":"month"
          }
        ]
      },
      [...]
    },
    "includes":[
      {
        "namespace":"http://schemas.xmlsoap.org/soap/encoding/",
        "location":"http://schemas.xmlsoap.org/soap/encoding/"
      }
    ]
    }

**Comment by simonjosefsson** [comment]
D'oh! maybe I was just confused about how to call the function... I should have set the option to `getPayrollFileUsers : { string : ["3", "5"] } }` instead of `getPayrollFileUsers : ["3", "5"] }`.

Now it formats the request just fine like SoapUI :thumbsup:

**Comment by herom** [comment]
Thanks a lot @simonjosefsson for keepin track of this issue - I guess it would be a good idea to write up something like a "Guideline on How to pass Arguments to SOAP Requests" as this is really confusing.
