### ISSUE TITLE
Soap Client Calls timeout

### ISSUE THREAD

**Issue by morious** [vpulim/node-soap#566]
Hi,
I am running into a strange timeout behavior when performing create client or making soap client calls from windows server 2008 R2. I am using node iis on IIS to run the server which uses soap client.

{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }

The timeout occurs after 20s. 
Setting a different timeout in options did not make an impact when set to above 20.

Any help will be appreciated.
M

**Comment by herom** [comment]
Do you also see this timeouts when you're not running your application on this particular server?

**Comment by morious** [comment]
I am running my application from a Mac and it works fast.
I am getting ready to try it from another windows machine thought.

**Comment by adrianvlupu** [comment]
how did you increase the timeout on the createClient method?

**Comment by herom** [comment]
@morious Are you able to rule out network topology (firewall settings, etc.) which may block outgoing requests of the server? I don't think that these timeout errors are a problem of `node-soap`, rather of the environment where it's run...

**Comment by morious** [comment]
@adrianvlupu, to increase the time out i used:
_getWsdlOptions = function() {
	return {
        wsdl_options: {
            rejectUnauthorized: false,
            timeout: 30000
        }
    };
}
soap.createClient(this.url, this._getWsdlOptions(), function(err, client) {
}.bind(this));

@herom, you are most likely correct i just haven't been able to prove that yet.
Running a WSDL call from Chrome on the same machine returned quickly, so i suspect it might be something to do with Certs.

**Comment by herom** [comment]
@morious are we able to close this?

**Comment by morious** [comment]
@herom, I have not been able to get down to the bottom of this yet. You can close it if you want and I can open a new issue when I get to the bottom of it. Thx.

**Comment by morious** [comment]
@herom, My investigation was delayed as i was out of the country - thx for not closing the issue yet. I am back now and I was able to run from a windows dev machine with no problem. The server i am having difficulties with is sitting on a different network though. I am still investigating.

**Comment by herom** [comment]
Thanks for the update @morious - I'm curious what's causing this timeouts too :smiley:

**Comment by morious** [comment]
@herom apparently setting a proxy on the soap call itself solved the issue.
I got the idea from: #138 .

Thx!
M

**Comment by herom** [comment]
Thanks for the information @morious - I think the opportunity of having a proxy is one of the things which should be incorporated into our README / Documentation. Do you mind opening a PR and provide a documentation on this well hidden feature? This would be awesome :+1:

**Comment by morious** [comment]
@herom absolutely. I am new to github as a contributor so i'll need to figure out what a PR is and i'll do it. :)

**Comment by herom** [comment]
awesome :+1:  PR === Pull Request :smiley_cat:

**Comment by herom** [comment]
Closing as solved
