### ISSUE TITLE
Node v0.12.0 support and Nonces

### ISSUE THREAD

**Issue by mrsteele** [vpulim/node-soap#573]
I am running Node v 0.12.0 and figured I would mention the following:
* I had to apply the following commit to get node-soap to work:
    * https://github.com/andrewbranch/node-soap/commit/41b11bdcd969aac66f6ab4dd7477a4662ae129c6
* Nonces in my wsdl are required with a PlainText password. This isn't capable currently so I had to manually add the password field in your WSSSecurity code.

**Comment by herom** [comment]
@mrsteele `node-soap` has released a new version (`v0.8.0`) which is now compatible with `node v0.12.0) - thanks go out to @andrewbranch.

Regarding your "Nonces with PlainText password" problem solution: we're open for PRs at any time :smiley:
