### ISSUE TITLE
SSL - Memory leak

### ISSUE THREAD

**Issue by WerVbn** [vpulim/node-soap#575]
I send every second a via SSL encrypted (self signed) SOAP message to a WCF server, which causes a significant memory leak, which causes a pretty high cpu usage because of the GC. I don't have the problem if I send the SOAP messages unencrypted, the memory usage is more or less stable. Which module within the node-soap module could cause the memory leak if I encrypt my messages? I use node v0.10.25 at a BBB.

**Comment by tesfel** [comment]
Maybe the connection is dropped for each method I call on the server?
