### ISSUE TITLE
extract the attachment of soap message

### ISSUE THREAD

**Issue by minyixie** [vpulim/node-soap#576]
I am new to use soap module and the version I am using should be the latest. 

I use the following code to get the image binary data(base64) from server.

soap.createClient(url, function(err, client) {  
    var args = [...]; //some properties  
    client.get_image_data(args , function(err,result, raw){
        console.log(result);
        console.log(raw);
    });
});

The return value of get_image_data() function is defined as base64 binary data on server.

For the result, I get the content ID, such as {href:"cid:http//whatever"} For the raw, I get the entire soap envelope but no attachmemt.

I search on the web, it said the binary data should somewhere after the envelope, is that right? If so, how can I get the binary data for the image?

Thanks for helps.

**Comment by longweiquan** [comment]
I encounter the same problem.

In my case, the web service return a PDF in base64 format at the end of the raw message. With SoapUI, I receive the full raw message and I can get the PDF from attachments.

But with node-soap, the PDF stream is truncated. And I don't know how to get the full raw message with node-soap.

Could you help me with the problem. Thanks for helps.

**Comment by minyixie** [comment]
Still, I have not got the attachment yet. But now I am trying the WS.Js,
hope it can help.

Node soap seems not work on attachment.

Regards

**Comment by stenersenberg** [comment]
@minyixie Did you get WS.Js to work with attachments?

**Comment by minyixie** [comment]
Yes, i did get the attachment by adding following line in the code:

encodeURIComponent = function(s) {return s}

Hope it is helpful.

Regards
Minyi
