### ISSUE TITLE
createClient from local file path

### ISSUE THREAD

**Issue by adrianvlupu** [vpulim/node-soap#582]
I am having some trouble creating a client. I am trying to connect to a very slow server and the createClient method frequently timeouts. I tried setting wsdl_options to higher value but it still timeouts.

So I figured I download and put the wsdl xml file locally and create the client from there.It stil timeouts ! Are there any other calls involved in the creation of a client except the wsdl endpoint?
 
Sorry for posting this as an issue.

**Comment by simonjosefsson** [comment]
Is the WSDL self-contained or does it have includes and/or imports?

**Comment by adrianvlupu** [comment]
I don't really know what that means but under <wsdl:types> there are a couple of xsd:import tags with a http:// schemaUrl

**Comment by simonjosefsson** [comment]
Namespaces often use URLs just as identifiers (because they are naturally unique) so that doesn't necessarily mean it's used to download a resource.
Are there any `location` attributes specified? See [w3 spec](http://www.w3.org/TR/wsdl#_document-n) for an example.

Another approach would be to just install wireshark and inspect the traffic as you create the client :wink:

**Comment by adrianvlupu** [comment]
Ok I think I get it now. The method checks all the external urls that's why it's taking so long and eventually timeouts.

How can I fix my code though? I have a module that initiates a client and exposes some methods that use it to my app. 
If the createClient method fails I have to restart my app a couple of times until the method is successful.

I'm sure there must be a better way of doing this

**Comment by adrianvlupu** [comment]
Yes there are a few <xsd:import schemaLocation="...."
I don't think I can do anything to avoid the timeout now :(

I may have to change the structure of my code.
I have a module that creates a soap client and exposes an object that uses that client.
If the create client method fails all I can do is restart the application and hope for it to work. 
I know there has to be a better pattern to make a module depend on a soap service but I'm really new to node and can't figure it out.

Should I put the createClient method on a recursive function so it tries until it succeeds?
