### ISSUE TITLE
Invalid docs for `server.authorizeConnection()`

### ISSUE THREAD

**Issue by sommestad** [vpulim/node-soap#583]
The docs for (server.authorizeConnection)[https://github.com/vpulim/node-soap#server-connection-authorization] state that the `req` object is being provided to the function. 

However, looking at the code, this is incorrect:

``` js
// lib/server.js:41
if (typeof self.authorizeConnection === 'function') {
  if (!self.authorizeConnection(req.connection.remoteAddress)) {
    res.end();
    return;
  }
}
```

It would be a lot better if the `req` was actually provided, rather than just providing the `removeAddress`, since that would enable more flexibility in terms of setting up authentication (e.g. if you'd want a separate unauthenticated path for health checks on the same server, `/ping`).

**Comment by herom** [comment]
@sommestad thanks a lot for raising this issue - Pull Requests are highly appreciated & welcome :+1: :smiley:
