### ISSUE TITLE
How to debug soap response on error?

### ISSUE THREAD

**Issue by kevbaker** [vpulim/node-soap#591]
I am getting a "TypeError: Cannot read property 'placeOrderResponse' of undefined" on my request to the SOAP API I'm abstracting.

The "placeOrderResponse" is obviously app specific.

I would like a way to see the full SOAP response, header status codes etc, so I can debug this. How would I go about this?

**Comment by herom** [comment]
Have you considered to subscribe to the [Client Events](https://github.com/vpulim/node-soap#client-events)?

**Comment by kevbaker** [comment]
Could you point me in the direction of some example code for this? Sounds liked cruft direction

**Comment by simonjosefsson** [comment]
given `client` created from `soap.createClient` one can do:

    client.on('request', function (xml) {
        console.log(xml)
    });

or you can inspect the unparsed html response like so:

    client.MyFunction(args, function(err, result, raw) {
        console.log(raw);
    });

**Comment by kevbaker** [comment]
Great! Very helpful!
