### ISSUE TITLE
Asynchronous soap requests mixed with node for loops

### ISSUE THREAD

**Issue by ramotswa** [vpulim/node-soap#592]
hi @herom,
Apologies about asking for help - hope you don't mind. Happy for you to just close this. 

I've seen the issue where you say that synchronous requests are not supported, but I was wondering if you could point me in the right direction with what I am trying to do. 

I am reading a csv file (using nodes csvtojson module) and storing that all in a json object. 
Then I iterate through the json object in a for loop, and for each record in the json object I want to execute 3 soap requests, which _have_ to happen one after the other. 

I think that last part is the crux, because what I am finding is that as the soap requests are async the for loop will iterate through pretty quickly and try to enter the soap requests again and again which is causing issues. I've been playing with 'promises' but unsure if that is quite the right way. 

thanks for any advice!
Ramo

**Comment by simonjosefsson** [comment]
I think the [async module](https://www.npmjs.com/package/async) is what you are looking for.
(Specifically the [waterfall](https://www.npmjs.com/package/async#waterfall) function)
