### ISSUE TITLE
Any way to override soap:address per request?

### ISSUE THREAD

**Issue by kevinohara80** [vpulim/node-soap#602]
I'm building a client for the Salesforce.com SOAP API's. I need the client library to be able to consume a single WSDL but override the `soap:address` per client request. This is because Salesforce has a large array of endpoints based on what instance your Salesforce.com org is on.

Is this possible? If not, are you open to a pull request?

**Comment by herom** [comment]
Please see https://github.com/vpulim/node-soap#options-optional section of our README - I guess this is what you want.

If this does not satisfy your needs or is just unusable for you - we're always open for Pull Requests as long as they are valuable to the whole project and a broad range of possible users and not only customized to a specific use case which is only used within a single project :+1:

**Comment by kevinohara80** [comment]
OK, that might work. Didn't realize you might be able to override the `uri` argument. I'll try it out today.

```
client.MyService.MyPort.MyFunction({name: 'value'}, function(err, result) {
  // result is a javascript object
}, { uri: 'https://my.uri.com/soap' })
```

**Comment by herom** [comment]
Please feel free to reopen if you have troubles with this solution. 

In general, it would be a very valuable addtion to our library, if we got something like a documentation page/webpage up and running, so people can read (and find!) what they are looking for - our README is a complete mess imho :cry:
