### ISSUE TITLE
release 0.9?

### ISSUE THREAD

**Issue by kirrg001** [vpulim/node-soap#605]
https://github.com/vpulim/node-soap/compare/v0.8.0...master
When do you plan to publish the new release?

Thanks!
kirrg001

**Comment by kirrg001** [comment]
ping

**Comment by herom** [comment]
@kirrg001 I understand that you're eager for a follow up release, but as I'm really short on time these months and I'm awaiting responses to a few (really few) PRs it could well be that a follow up release is not made before mid next week (should be around March 25th). :+1: 

In the last time I'm pretty self on my own at keeping this repository "moderated", so thinks have slowed down a bit and I'm really sorry. Please, if you need new features use our master branch for now.

**Comment by kirrg001** [comment]
Cool thanks for update. 
I just needed a date because i need an important fix from master. will use master branch.

**Comment by herom** [comment]
As I wrote #656 I finally made the `0.9.0` release and I'll work constantly to bring up a `0.10.0` release soon. Sorry for the inconvenience.

**Comment by kirrg001** [comment]
like
