### ISSUE TITLE
Extended objects incorrectly parsed

### ISSUE THREAD

**Issue by kevinohara80** [vpulim/node-soap#606]
I'm currently working with the Salesforce.com Metadata API. I'm calling their `readMetadata` method that return an array of Metadata objects. The Metadata complexType is a base for many other metadata types.

I expected that the js object returned would have all of the elements casted to their correct types but they are mostly being returned as strings. All other SOAP methods that do not return extended complexTypes are parsing just fine.

For example, in the output below the `enableActivities` is an element in the CustomObject metadata type and is supposed to be a boolean. 

``` js
[ { '$attributes': { 'xsi:type': 'CustomObject' },
    fullName: 'Test_Object__c',
    actionOverrides:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    compactLayoutAssignment: 'SYSTEM',
    deploymentStatus: 'Deployed',
    enableActivities: 'false',
    enableBulkApi: 'true',
    enableFeeds: 'false',
    enableHistory: 'false',
    enableReports: 'false',
    enableSharing: 'true',
    enableStreamingApi: 'true',
    fields: [ [Object], [Object], [Object], [Object] ],
    label: 'Test Object',
    listViews:
     { fullName: 'All',
       columns: [Object],
       filterScope: 'Everything',
       label: 'All' },
    nameField:
     { displayFormat: '{0}',
       label: 'Test Object Name',
       type: 'AutoNumber' },
    pluralLabel: 'Test Objects',
    searchLayouts: {},
    sharingModel: 'ReadWrite' } ]
```

Here are the Metadata and CustomObject complex types for reference from the WSDL:

``` xml
<xsd:complexType name="Metadata">
  <xsd:sequence>
    <xsd:element name="fullName" minOccurs="0" type="xsd:string"/>
  </xsd:sequence>
</xsd:complexType>
```

``` xml
<xsd:complexType name="CustomObject">
  <xsd:complexContent>
    <xsd:extension base="tns:Metadata">
      <xsd:sequence>
        <xsd:element name="actionOverrides" minOccurs="0" maxOccurs="unbounded" type="tns:ActionOverride"/>
        <xsd:element name="articleTypeChannelDisplay" minOccurs="0" type="tns:ArticleTypeChannelDisplay"/>
        <xsd:element name="businessProcesses" minOccurs="0" maxOccurs="unbounded" type="tns:BusinessProcess"/>
        <xsd:element name="compactLayoutAssignment" minOccurs="0" type="xsd:string"/>
        <xsd:element name="compactLayouts" minOccurs="0" maxOccurs="unbounded" type="tns:CompactLayout"/>
        <xsd:element name="customHelp" minOccurs="0" type="xsd:string"/>
        <xsd:element name="customHelpPage" minOccurs="0" type="xsd:string"/>
        <xsd:element name="customSettingsType" minOccurs="0" type="tns:CustomSettingsType"/>
        <xsd:element name="customSettingsVisibility" minOccurs="0" type="tns:CustomSettingsVisibility"/>
        <xsd:element name="deploymentStatus" minOccurs="0" type="tns:DeploymentStatus"/>
        <xsd:element name="deprecated" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="description" minOccurs="0" type="xsd:string"/>
        <xsd:element name="enableActivities" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="enableBulkApi" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="enableDivisions" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="enableEnhancedLookup" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="enableFeeds" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="enableHistory" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="enableReports" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="enableSharing" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="enableStreamingApi" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="externalDataSource" minOccurs="0" type="xsd:string"/>
        <xsd:element name="externalName" minOccurs="0" type="xsd:string"/>
        <xsd:element name="externalRepository" minOccurs="0" type="xsd:string"/>
        <xsd:element name="externalSharingModel" minOccurs="0" type="tns:SharingModel"/>
        <xsd:element name="fieldSets" minOccurs="0" maxOccurs="unbounded" type="tns:FieldSet"/>
        <xsd:element name="fields" minOccurs="0" maxOccurs="unbounded" type="tns:CustomField"/>
        <xsd:element name="gender" minOccurs="0" type="tns:Gender"/>
        <xsd:element name="historyRetentionPolicy" minOccurs="0" type="tns:HistoryRetentionPolicy"/>
        <xsd:element name="household" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="label" minOccurs="0" type="xsd:string"/>
        <xsd:element name="listViews" minOccurs="0" maxOccurs="unbounded" type="tns:ListView"/>
        <xsd:element name="nameField" minOccurs="0" type="tns:CustomField"/>
        <xsd:element name="pluralLabel" minOccurs="0" type="xsd:string"/>
        <xsd:element name="recordTypeTrackFeedHistory" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="recordTypeTrackHistory" minOccurs="0" type="xsd:boolean"/>
        <xsd:element name="recordTypes" minOccurs="0" maxOccurs="unbounded" type="tns:RecordType"/>
        <xsd:element name="searchLayouts" minOccurs="0" type="tns:SearchLayouts"/>
        <xsd:element name="sharingModel" minOccurs="0" type="tns:SharingModel"/>
        <xsd:element name="sharingReasons" minOccurs="0" maxOccurs="unbounded" type="tns:SharingReason"/>
        <xsd:element name="sharingRecalculations" minOccurs="0" maxOccurs="unbounded" type="tns:SharingRecalculation"/>
        <xsd:element name="startsWith" minOccurs="0" type="tns:StartsWith"/>
        <xsd:element name="validationRules" minOccurs="0" maxOccurs="unbounded" type="tns:ValidationRule"/>
        <xsd:element name="webLinks" minOccurs="0" maxOccurs="unbounded" type="tns:WebLink"/>
      </xsd:sequence>
    </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>
```

Is there something that I need to do to fix this?

Here is a copy of the full wsdl: https://gist.github.com/kevinohara80/073fe2c824b6c006b120

**Comment by shraddha22** [comment]
I am trying to create custom object in salesforce using salesforce metadata api  and calling from node client. For object creation i am using metadata api method createMetadata() but when trying to call , i am getting the following error-
ERROR:
  body: '<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="
http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><soapenv:Fault><faultco
de>soapenv:Client</faultcode><faultstring>Must specify a {http://www.w3.org/2001
/XMLSchema-instance}type attribute value for the {http://soap.sforce.com/2006/04
/metadata}metadata element</faultstring></soapenv:Fault></soapenv:Body></soapenv
:Envelope>' }

i am defining the xsi type attribute in my code but i dont know why i am getting this error. Can someone help me with this
Below is the code i have written:

'var soap = require('soap');
var _ = require('underscore');
var url = './metadata api/sf-partner.wsdl';

soap.createClient(url, function(err, client) {
    client.login({
        username: '#####',
        password: '#####'
    }, function(err, result, raw) {
        if (err) console.log(err);
        if (result) {
            console.log(result.result);
        }

        metaUrl = './metadata api/sf-metadata.wsdl';
        soap.createClient(metaUrl, function(err, metaClient) {
            if (err)
                throw err;

            metaClient.setEndpoint(result.result.metadataServerUrl);
            var sessionId = [];
            sessionId.push('<met:SessionHeader  xmlns:met="http://soap.sforce.com/2006/04/metadata">');
            sessionId.push('<met:sessionId>' + result.result.sessionId + '</met:sessionId>');
            sessionId.push('</met:SessionHeader>');

            metaClient.addSoapHeader(sessionId.join("\n"));


            var metadata = [{
                fullname: 'abc'
            }];
            metadata2 = _.map(metadata, function(value) {
                value['@xsi:type'] = 'CustomObject'
                return value;
            });

            metaClient.createMetadata({
                metadata: metadata
            }, function(err, result, raw, soapHeader) {

                if (err) {

                    console.log(err);
                }
                if (!err && result) {

                    console.log(result);
                }
            });


        });


    });
});
'
