### ISSUE TITLE
Async Fault not working

### ISSUE THREAD

**Issue by ghughal** [vpulim/node-soap#613]
I updated server-test.js to throw Fault exception from an async function but it doesn't seem to be working. Is this a bug or I should be handling this some other way?

``` javascript
    if (args.tickerSymbol === 'trigger error') {
        throw new Error('triggered server error');
    } else if (args.tickerSymbol === 'SOAP Fault') {
        console.log("before timeout");
        setTimeout(function() {
            console.log("throwing Fault exception after timeout");
            throw {
                Fault: {
                    Code: {
                        Value: "soap:Sender",
                        Subcode: { value: "rpc:BadArguments" }
                    },
                    Reason: { Text: "Processing Error" }
                }
            }
        }, 0);
    } else {
        return { price: 19.56 };
    }
```

Output:

```
before timeout
throwing Fault exception after timeout

/tmp/soap/test.js:30
                        throw {
                        ^
[object Object]
```

**Comment by ghughal** [comment]
One more thing I noticed was when soap fault is thrown the HTTP status code is 200 but as per [SOAP spec](http://www.w3.org/TR/soap12-part2/#tabresstatereccodes) it should be either 500/400 and there is no way to specify that.

I've been playing with server.js and I think both of these issues can be fixed by extending callback arguments like this:

```javascript
        setTimeout(function() {
            cb(null, fault, 500);
        }, 0);
```

I'll try to submit a pull request for this.

**Comment by brodin** [comment]
Think this is solved by https://github.com/vpulim/node-soap/pull/641
