### ISSUE TITLE
Ignore adding a namespace when one is already provided

### ISSUE THREAD

**Issue by acabrera4k** [vpulim/node-soap#621]
So for example:

``` javascript
var customer = {
      'ns6:isPerson': {
        attributes: {'xsi:type': 'xsd:boolean'},
        $value: 'true'
      }
}
```

where ns6 is a namespace I defined. When passing this through node-soap, I get back a namespace that was found through the wsdl and that gets added to the xml. 

``` xml
<platformCore:ns6:isPerson xmlns:platformCore="urn:core_2014_2.platform.webservices.netsuite.com"xsi:type="xsd:boolean">true</platformCore:ns6:isPerson>
```

as opposed to just ns6. The issue is that the namespace that was given though node-soap is incorrect which makes the xml invalid. I have a fix that will use the provided namespace (ns6) and not add 'platformCore'. Is this something that you think will be useful to other users? If so, I will make a pull request and go from there.

Thanks!

**Comment by alistairg** [comment]
I would certainly find that useful - I'm having to pass manually entered, pre-written XML to work around this issue... :|
