### ISSUE TITLE
Namespace for a function call

### ISSUE THREAD

**Issue by darrylc** [vpulim/node-soap#640]
Hello,

I could very well be doing something wrong, but I'm trying to access a third party SOAP API that has a namespace for their functions.

```
<soapenv:Envelope ...>
   <soapenv:Header/>
   <soapenv:Body>
      <impl:getPricing>
      </impl:getPricing>
   </soapenv:Body>
</soapenv:Envelope>
```

I'm having trouble figuring out how to add the "impl:" before "getPricing".  Any assistance would be much appreciated!

Thanks,

Darryl

**Comment by joeandaverde** [comment]
+1

**Comment by mkko** [comment]
+1

**Comment by luvaas** [comment]
+1

**Comment by JulienYo** [comment]
+1

**Comment by juansev** [comment]
+1

**Comment by tandrew** [comment]
+1

**Comment by ischraub** [comment]
+1

**Comment by qlonik** [comment]
+1

**Comment by geoffreyburdett** [comment]
+1

**Comment by alistairg** [comment]
+1

**Comment by geoffreyburdett** [comment]
Here's my hack to deal with the namespace, pass the ignoredNamespaces the soap.createClient options.

{
    "ignoredNamespaces": {
        namespaces: [ns']
    },
}
And then add the namespace manually. It's ugly, but it works.

{
...
    "impl:getPricing": "foobar"
...
}

**Comment by alistairg** [comment]
@geoffreyburdett - thankyou! I don't suppose you worked out how to add an additional namespace to the Soap Envelope as well, did you?....

**Comment by jpdewing** [comment]
Have a look at https://github.com/vpulim/node-soap/issues/672 its a bit of a hack but you can add an additional namespace.

**Comment by carlos22** [comment]
@geoffreyburdett can you give a better example? How can I add the namespace manually?

**Comment by geoffreyburdett** [comment]
Add the namespace to the property key
{"impl:getPricing": "foobar"}

**Comment by pselibas** [comment]
+ 1
