### ISSUE TITLE
Need to obtain URL path from incoming soap request.

### ISSUE THREAD

**Issue by fred-yatzeck-robomq** [vpulim/node-soap#643]
Hello,
I'm trying to subscribe to server 'request' events in order to obtain the incoming request URL path from the request object.  Our web service application is bound to multiple endpoint URLs, therefore, we need to know which URL the request was received on.
With this test example I'm trying, event is not received, is there anything I am missing?  What's interesting is I am able to subscribe to and receive the 'headers' event using similar code.

var s = soap.listen(server, sitePath, soapService, xml);
s.on('request', function (request, methodName) {
    console.log("Received request event.");
});

As a plan B, I had to locally modify server.js adding URL pathname to the service method call as follows:

var result = method(args, handleResult, options.headers, pathName);

Is there any other way I can obtain the URL path during or before the soap service call without requiring update to server.js?

**Comment by fyatzeck** [comment]
I am updating the title and description of issue given we have know exactly what is needed to obtain the request URL path from incoming soap request.  Therefore, plan to submit a pull request with change needed to support this.

We see no other mechanism to obtain this other than adding it to function call as part of soap service definition.  We found adding the URL path as "pathName" as follows when invoked by server.js solves our issue. 

var result = method(args, handleResult, options.headers, pathName);

It is critical to receive this pathName by our server application as it must bind and listen to multiple incoming paths.  We need to make processing decisions based on fields contained within this path.  As far as compatibility, we believe adding the pathName as last argument to function call should not impact exising API.
