### ISSUE TITLE
TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by Zenitram-Oriaj** [vpulim/node-soap#646]
I am getting this issue when trying to convert a Novell Groupwise Soap Service WSDL file using your library:
```
if (Object.keys(obj).length > 0) {
                              ^
TypeError: Object.keys called on non-object
```

Now I partially resolved this issue by using a "try-catch" in the wsdl.js lib file.

```
 function extend(base, obj) {
   try {
     if(Object.keys(obj).length > 0) {
       Object.keys(obj).forEach(function(key) {
       if(!base.hasOwnProperty(key))
         base[key] = obj[key];
       });
   } else {
 }
 return base;
 }  catch(e) {
   console.error('-----------------------------');
   console.error(e);
   console.error(obj);
   return base;
 }
}
```
Though most of everything returns fine now, i do get three errors:
```
-----------------------------
[TypeError: Object.keys called on non-object]
StatusTrackingOptions|xs:string|None,Delivered,DeliveredAndOpened,All
-----------------------------
[TypeError: Object.keys called on non-object]
uid|xs:string|pattern
-----------------------------
[TypeError: Object.keys called on non-object]
WeekDay|xs:string|Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday

```
I have run the wsdl file through an online WSDL validation program and it passes.

The link below is to the wsdl file:
https://www.dropbox.com/sh/td5iil3qb2k07tm/AABvhEO4EffLOKzh1IIZ4k0Ea?dl=0
(Note: I compiled it into a single file as the original was one wsdl file and three xsd files that get imported into the main wsdl file. They are included in the folder called "pre-compiled").

This link goes to the original Novell site for more detail information of this SOAP service:
https://www.novell.com/developer/ndk/groupwise/groupwise_web_service_%28soap%29.html

I have used you module with other WSDL files and it works great. Just having an issue with this one.

**Comment by pentode** [comment]
Hi,

  This has been fixed in the current github repository; I verified the error using v0.8.0 from npmjs.org and verified that it doesn't occur using current from github.  Until the maintainers publish another release to npmjs.org, you'll have to use node-soap from github...

```
npm install --save vpulim/node-soap
```

**Comment by Zenitram-Oriaj** [comment]
My apologies. I made an assumption that the version I pulled directly from the npm repository was the current version.

Yes, after removing the version I had installed and then using the provided npm install method, the issue seems to be resolved.

Thank you for your time on this.

**Comment by pentode** [comment]
No worries.

`<general-rant>`
I've pretty much given up on using the public npm repository because I'm pulling so many dependencies from github and a few with non-merged changes...[sinopia](https://github.com/rlidwka/sinopia) to the rescue!
`</general-rant>`
