### ISSUE TITLE
Sorry for my abscence - I'll work through the issues since my last activity step by step...

### ISSUE THREAD

**Issue by herom** [vpulim/node-soap#656]
I'm really sorry for the really long time without any response from me. I don't want to let the community down or let this library "die". I was unable to take any actions on my contributions due to private and personal reasons and I was hoping that any of the other maintainers would take over and keep it running. .. but obviously I was wrong.

Sorry again for all the inconvenience you had while I was absent & unresponsive. I'll make my way through issues and PRs constantly as good as I can.

If anybody feels like he wants to help to keep this library alive and help out as a maintainer, please respond within this issue or send me a message. I'm not able to add other maintainers (I guess), but I think it might be possible to reach out to @vpulim and ask him to add others too as the main contributor @jsdevel is also busy with other projects at the moment.

**Comment by simonjosefsson** [comment]
You're doing good work here, unfortunately I don't have the time (nor the knowledge I suspect :wink:) to help share the maintenance burden.
Just wanted to say thank you and give you some encouragement :+1:

**Comment by herom** [comment]
Thanks a lot for your kind words :smiley_cat: and also thanks a lot for your contributions (I see that you are one of the few who do answer questions in issues here :+1: )

**Comment by pentode** [comment]
Thanks for putting your time into node-soap.  I'd offer to help, because I will soon be putting node-soap into production in a number of apps, but I suspect you'd want someone with more knowledge of the SOAP protocol(s).

Any comments on https://github.com/vpulim/node-soap/pull/639?

cheers!
