### ISSUE TITLE
Set Proxy in createClient

### ISSUE THREAD

**Issue by bartbrat** [vpulim/node-soap#682]
I have same troubble with set proxy in createClient... it does'nt work..

var options = {
    proxy: 'http://usernam:password@xxx.xx.xx.xx:pppp',
    strictSSL: false
};

soap.createClient(config.url, options, function(err, client) {
  if (err) {
    l4j.error('[createClient] error: ' + err);
    process.exit();
  } 
 ...
});

**Comment by ispyonyou** [comment]
Try to use wsdl_options.proxy instead proxy. It works for me.
```
var soap = require('soap');

var wsdl_url = 'http://www.morpher.ru/WebServices/Morpher.asmx?WSDL';
var my_proxy = 'http://192.168.222.100:3128'

var createClientOptions = {
    wsdl_options: {
        proxy: my_proxy
    }
}
var options = {
    proxy: my_proxy
}

function getFormsResponse(err, result){
    console.log(result);
}

soap.createClient(wsdl_url, createClientOptions, function (err, client) {
    console.log('client created')
    client.GetForms({ s: 'привет' }, getFormsResponse, options);
});
```

**Comment by k7sleeper** [comment]
For me, too, but `wsdl_options` is not a very intuitive name :-(
