### ISSUE TITLE
Extracting the Response as JSON object from the Soap Body

### ISSUE THREAD

**Issue by ksachdeva** [vpulim/node-soap#687]
Hi,

Not able to see and figure out the way to extract the Soap response as the JSON object. Calling response.toJSON() returns the body property whose value is raw xml/soap. 

Are we suppose to use a library like xml2json to convert the response body ?.

Please guide.

Regards
Kapil

**Comment by ltcdnunez** [comment]
This worked for me:

```js
...
client.Method(args, function(err, res) {
  ...
  res.response.toJSON();
});
```

**Comment by ksachdeva** [comment]
On my side it fails with toJSON() can not be invoked on undefined. I know that toJSON() is a method on res i.e res.toJSON(). However this returns a json object with "statusCode", "body" etc properties with body containing the raw soap message. I am interested in getting a response object extracted from soap:body as a json object. I know that I could do this by using xml2json library etc but was wondering if it was natively supported by node-soap

**Comment by ksachdeva** [comment]
Found the issue. The Soap message returned by my service has an invalid XML element that make sax library throw an error and hence the body is not parsed.
