### ISSUE TITLE
Wrapper Element around SOAP method doesn't include 'ws:'

### ISSUE THREAD

**Issue by whitef0x0** [vpulim/node-soap#695]
I'm having problems with a SOAP request. I'm getting `Unexpected wrapper element [element name found.` for my client Method.

Looking at my working SoapUI request it seems like SoapUI is appending a 'ws:' to my wrapper element and node-soap isn't.

I.e. this SoapUI request works
`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://ws.oscarehr.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <ws:login>
         
         <arg0>aoeaeo</arg0>
         
         <arg1>aoeaoe</arg1>
      </ws:login>
   </soapenv:Body>
</soapenv:Envelope>
`

However if I remove the `:ws` it doesn't work and generates same error as node-soap.
`
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://ws.oscarehr.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <login>
         
         <arg0>aoeaeo</arg0>
         
         <arg1>aoeaoe</arg1>
      </login>
   </soapenv:Body>
</soapenv:Envelope>
`

My code that causes my error  is below

`soap.createClient(__dirname+'/mywsdl.xml', function(err, client) {
       	args_login = {arg0: 'davieb', arg1: 'Temppass1'};
	client.login(args_login, function (err, result) {
		console.log(result.toJSON());
	});

});`

Here is my WSDL file

`<?xml version="1.0" encoding="UTF-8"?>

<definitions>
  <types>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="unqualified" >
      <xs:element name="login" type="tns:login"/>
      <xs:element name="loginResponse" type="tns:loginResponse"/>
      <xs:complexType name="login">
        <xs:sequence>
          <xs:element minOccurs="0" name="arg0" type="xs:string"/>
          <xs:element minOccurs="0" name="arg1" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:complexType name="loginResponse">
        <xs:sequence>
          <xs:element minOccurs="0" name="return" type="tns:loginResultTransfer"/>
        </xs:sequence>
      </xs:complexType>
      <xs:complexType final="extension restriction" name="loginResultTransfer">
        <xs:sequence>
          <xs:element minOccurs="0" name="securityId" type="xs:int"/>
          <xs:element minOccurs="0" name="securityTokenKey" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="NotAuthorisedException" type="tns:NotAuthorisedException"/>
      <xs:complexType name="NotAuthorisedException">
        <xs:sequence/>
      </xs:complexType>
    </xs:schema>
  </types>
  <message name="loginResponse">
    <part element="tns:loginResponse" name="parameters">
    </part>
  </message>
  <message name="login">
    <part element="tns:login" name="parameters">
    </part>
  </message>
  <message name="NotAuthorisedException">
    <part element="tns:NotAuthorisedException" name="NotAuthorisedException">
    </part>
  </message>
  <portType name="LoginWs">
    <operation name="login">
      <input message="tns:login" name="login">
      </input>
      <output message="tns:loginResponse" name="loginResponse">
      </output>
      <fault message="tns:NotAuthorisedException" name="NotAuthorisedException">
      </fault>
    </operation>
  </portType>
  <binding name="LoginWsServiceSoapBinding" type="tns:LoginWs">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="login">
      <soap:operation soapAction="" style="document"/>
      <input name="login">
        <soap:body use="literal"/>
      </input>
      <output name="loginResponse">
        <soap:body use="literal"/>
      </output>
      <fault name="NotAuthorisedException">
        <soap:fault name="NotAuthorisedException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="LoginWsService">
    <port binding="tns:LoginWsServiceSoapBinding" name="LoginWsPort">
      <soap:address location="https://aoeuaoe.com/eoauae/wsdlService"/>
    </port>
  </service>
</definitions>
`

I've read through the old issues that pertained to similar errors like this and can't find anything relevant to my problem as it seems like wrapper element issues were fixed many, many versions ago.

Is anyone else having this problem or is it just me?

**Comment by whitef0x0** [comment]
Never mind. Fixed it.

**Comment by pradeep-mishra** [comment]
is it fixed? , coz i am having same issue

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>Unexpected wrapper element getTags found.   Expected {http://www.some.com/webservices/SoapService}getTags.</faultstring></soap:Fault></soap:Body></soap:Envelope>' },
  body: '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>Unexpected wrapper element getTags found.   Expected {http://www.some.com/webservices/SoapService}getTags.</faultstring></soap:Fault></soap:Body></soap:Envelope>

**Comment by whitef0x0** [comment]
Yep it was fixed. Look at previous issues on similar subjects.
