### ISSUE TITLE
Error is not handled if HTTP response does not accomodate to WSDL schema

### ISSUE THREAD

**Issue by franza** [vpulim/node-soap#696]
In case SOAP service returns a response which doesn't mach with WSDL schema we'll get unhandled error. In versions prior to 0.7 `soap` had next logic:

``` javascript
// v < 0.7, wsdl.js - WSDL.prototype.xmlToObject
var body = root.Envelope.Body;
if (body.Fault) {
  var error = new Error(body.Fault.faultcode + ': ' + body.Fault.faultstring + (body.Fault.detail ? ': ' + body.Fault.detail : ''));
  error.root = root;
  throw error;
}
return root.Envelope;
```

Here code throws "Cannot read property 'Body' of undefined" at the very first line. This exception is handled in `client.js`'s `try/catch` statement and is provided into the callback of SOAP method.

But starting v 0.7 we have here:

``` javascript
// v >= 0.7, wsdl.js - WSDL.prototype.xmlToObject
if (root.Envelope) {
  var body = root.Envelope.Body;
  if (body.Fault) {
    var error = new Error(body.Fault.faultcode + ': ' + body.Fault.faultstring + (body.Fault.detail ? ': ' + body.Fault.detail : ''));
    error.root = root;
    throw error;
  }
  return root.Envelope;
}
return root;
```

But here we don't touch properties of undefined `root.Envelope`. Later in `client.js` we are doing this line of code

``` javascript
result = obj.Body[output.$name];
```

which invokes `Body` property of `undefined`. This crashes the node process.

Could anyone help me with this issue? In fact I'm feeling like adding additional check or `try/catch` in `client.js`.

**Comment by skimsey** [comment]
I'm running into the same issue, franza ~ would love to look at your patch, should you decide to write one.

**Comment by skimsey** [comment]
Check out this code update to WSDL.JS - it seems to be helping me: https://github.com/piotr-gawlowski/node-soap/pull/1
