### ISSUE TITLE
"H E L P" Error: Cannot parse response 

### ISSUE THREAD

**Issue by Hamatek** [vpulim/node-soap#702]
Hello,

I have been trying to work my way with Meteor-soap/node-soap for hourssss but I wasn't able to figure out why every time I call a method I get : Error: Cannot parse response .

When create Client without any options : `Soap.createClient(url)`
It seems the  to be working  properly since `client.describe()` 
return all the method of my WSDL 

to call my method I use this syntax `Client.service.port.method(args)`

Also I know that the SOAP Webservice works fine because I have it run in production on a PHP website and I use tool like SOAPUI 5, they both work perfectly without any special options.

What might be wrong is that maybe I may be missing some options ? When I create client or call method ? OR Maybe it's something related to the `client.service.port.method` syntax rather than just `client.MyFunction(args)` ? ...

I really am clueless about how to debug this soap response issue, any help would be greatly appreciated !

**Comment by aol-nnov** [comment]
same thing here. I end up with empty ```body``` in ```HttpClient.prototype.handleResponse```
I might be doing something terribly wrong, but I do not know, what exaclty..

**Comment by aol-nnov** [comment]
@jsdevel sorry for disturbing you, but could you shed some light on it?
thanks in advice!

**Comment by Hamatek** [comment]
@aol-nnov I fixed my issue, in my case  node-soap was adding the same namespace 150 times to my xml envelope's header ... this kind of behavior doesn't seems necessary so i fixed it in the `WSDL.prototype._xmlnsMap = function()`. Also when I pass my args to the client I manually specify the datacontract namespace because node-soap doesn't do it. for example I append "q1" to number

args= { p:{"q1:Number":"123456"}

I hope my case helps,

Cheers

**Comment by aol-nnov** [comment]
No, unfortunately, it does not help me..
I've also noticed that same namespace is added multiple times (with different prefixes), but it does not interfere.
I get raw request constructed by node-soap 
```
client.on('request', function (xml) {
                console.log('req xml', xml);
});
```

And then copy it over to SoapUI without any modifications. And it works there like a charm.. ```body``` in ```handleResponse``` Is empty though... Weird..

**Comment by aol-nnov** [comment]
I've made it finally. It mainly fails due to wrong content-type header and namespace as I'm consuming a soap 1.2 service.
It is somewhat related to PR #721, but my fixes are [different](https://gist.github.com/aol-nnov/1d86cf254b0e94dfbf3d)
I've tried the fix from aforementioned PR, but it does not work for me.

**Comment by jsdevel** [comment]
@aol-nnov a pull request to fix this would be greatly appreciated.

**Comment by aol-nnov** [comment]
@jsdevel I'm not sure if it will be back compatible with 1.1 spec. I'm not that familiar with it, unfortunately.
But I can make a PR if you'd like to.

**Comment by jsdevel** [comment]
@aol-nnov if you can provide a `request-response-sample` as a test, then backcompat will be ensured.

**Comment by ChopperLee2011** [comment]
i use the new version 0.10.1, also have this issue:
 the xml content return in the `request ` event can get right xml response in SoapUI, but return 'Error: Cannot parse response' in this lib's `Client.service.port.method`
and change the content-type and content-length can fix it. can u give me more adivse? @jsdevel
