### ISSUE TITLE
BUG: multiple parts in input

### ISSUE THREAD

**Issue by SteCla** [vpulim/node-soap#704]
Packet doesn't support multiple parts in 'input' element. Only takes first one. First one was a header one, second one for body so saved wsdl locally, switched their place and accessed the header-input part with the addsoapheader function.
This is the wsdl file for future testing:
http://kbopub-acc.economie.fgov.be/kbopubws030000/services/wsKBOPub?wsdl

**Comment by herom** [comment]
If you have a fix for this, please feel free to submit a PR :+1:
