### ISSUE TITLE
Possible problem with empty xml nodes

### ISSUE THREAD

**Issue by anvk** [vpulim/node-soap#707]
webservice returns this XML back

```xml
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Body>
    <QueryCustomerResponse xmlns="http://tempuri.org/">
      <QueryCustomerResult xmlns:a="http://schemas.datacontract.org/2004/07/" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
        <a:Accepted>true</a:Accepted>
        <a:Customer>
          <a:CITY>Markham</a:CITY>
          <a:ENHANCED_CAPABLE>N</a:ENHANCED_CAPABLE>
          <a:FIRST_NAME/>
          <a:LAST_DATETIME_MODIFIED>Aug 31 2015  6:55PM</a:LAST_DATETIME_MODIFIED>
          <a:LAST_DATETIME_MODIFIED_UNIXTIME>1441047313</a:LAST_DATETIME_MODIFIED_UNIXTIME>
          <a:LAST_NAME/>
          <a:OTHER_ADDRESS_INFO/>
          <a:PHONE_NUMBER>6479250483</a:PHONE_NUMBER>
          <a:POSTAL_CODE_ZIP>L6C2C6</a:POSTAL_CODE_ZIP>
          <a:PROVINCE_STATE>ON</a:PROVINCE_STATE>
          <a:STREET_NAME>Trail Ridge Lane</a:STREET_NAME>
          <a:STREET_NUMBER>1234</a:STREET_NUMBER>
          <a:SUITE_APT/>
          <a:VENDOR_CODE>273</a:VENDOR_CODE>
        </a:Customer>
        <a:Errors/>
        <a:VendorDumpURL i:nil="true"/>
      </QueryCustomerResult>
    </QueryCustomerResponse>
  </s:Body>
</s:Envelope>

```

This is what I see in `result` object:

```
{ QueryCustomerResult: 
   { Accepted: 'true',
     Customer: 
      { CITY: 'Markham',
        ENHANCED_CAPABLE: 'N',
        FIRST_NAME: {},
        LAST_DATETIME_MODIFIED: 'Aug 31 2015  6:55PM',
        LAST_DATETIME_MODIFIED_UNIXTIME: '1441047313',
        LAST_NAME: {},
        OTHER_ADDRESS_INFO: {},
        PHONE_NUMBER: '6479250483',
        POSTAL_CODE_ZIP: 'L6C2C6',
        PROVINCE_STATE: 'ON',
        STREET_NAME: 'Trail Ridge Lane',
        STREET_NUMBER: '1234',
        SUITE_APT: {},
        VENDOR_CODE: '273' },
     Errors: {} } }
```
You can see how `<a:FIRST_NAME/>` is transformed into `{}` empty object. I would assume it should be empty string or maybe undefined, but why an empty object ?

**Comment by PetrSnobelt** [comment]
+1
It will be great if is possible to return null or emptystring instead of {}

**Comment by herom** [comment]
@anvk @PetrSnobelt a PR to fix this behaviour is highly welcome :smiley: :+1:

**Comment by anvk** [comment]
@herom sure but what is an expected behavior? Should it be undefined or null or an empty string ?

**Comment by jsdevel** [comment]
I vote `null`.

**Comment by anvk** [comment]
I vote `null` as well.
Just of curiosity - is there any case when XML will produce an empty object? I think there is no such possibility (unless I'm wrong)

**Comment by jsdevel** [comment]
Not that I'm aware of.

On thinking about this further, it does seem that this is a breaking change for existing scripts that aren't used to `null` being returned.  Likely isn't that big of a migration path to the next version, but are we certain we really want `null` to be returned?  I also wonder if in some cases the presence of an element signifies something in existing APIs.

**Comment by PetrSnobelt** [comment]
I also think null is better then empty object

**Comment by anvk** [comment]
> but are we certain we really want null to be returned?

I'm pretty sure you do. Lots of consumers of this library would rather prefer to do a basic check to see if a property is falsy (or null) rather than importing an extra library to compare value to an empty object OR any other weird comparison implementation.

**Comment by jsdevel** [comment]
+1.  Let's take this up in #733
