### ISSUE TITLE
WSDL sample

### ISSUE THREAD

**Issue by wmmihaa** [vpulim/node-soap#711]
First thanks for taking the time to share your SOAP library. I'm struggling a bit to get the mapping between my js and the wsdl. I'm looking at the soap.listen samples provided on npm and github, and it would really help if you had a simple working sample of perhaps if you could provide the wsdl for the sample (myservice.wsdl).
Thanks 
Mikael

**Comment by jsdevel** [comment]
Checkout the tests for server examples.  I believe that's what you're after.  If you find something that's not in the README, please issue a PR to get your example included.  Thanks!

**Comment by 360disrupt** [comment]
+1, do I have to write the wsdl from scratch? Is there a generator out there? 

I googled for 30min+ and did not find anything besides soapUi (which is not working on my Mac) and tremendously expensive enterprise software.
