### ISSUE TITLE
createClient() takes a very long time to connect

### ISSUE THREAD

**Issue by alixaxel** [vpulim/node-soap#713]
I'm trying to consume a SOAP service from D&B, here's the code snippet:

```javascript
var soap = require('soap');

soap.createClient('http://mktinterface.dnb.com/wsgateway/services/DNBWebServiceGateway?wsdl', function (error, client) {
    if (error) {
        console.error(error);
    }

    console.log('SOAP Connected', client.describe());
});
```

For the first call, it takes over 3 minutes to establish the initial connection, after that it's super quick.

If I try the equivalent code in PHP, it returns the available SOAP functions right away.

I've also tried to save and load the WSDL locally from the file system, but it doesn't help at all.

**Comment by herom** [comment]
Thanks for bringing this issue up @alixaxel - we know that we have some performance problems. If you have time it would be great if you would accept the challenge and try to tune the code by submitting  a PR :+1:

**Comment by sathishbabu007** [comment]
Any update on this ?

**Comment by herom** [comment]
As I mentioned before - this is an open source project and `node-soap` is kept alive by its awesome community :smiley:

So, if you feel like you can contribute something back to the wonderful library you're using, please open a PR so that we can make `node-soap` more awesome :+1:

**Comment by alixaxel** [comment]
@herom Sorry unfortunately my free time doesn't allow me to take this challenge ATM.

**Comment by herom** [comment]
no problem @alixaxel - I mostly replied to @sathishbabu007 because he was asking about the current status :smiley:
