### ISSUE TITLE
Content-Type in header as 'application/soap+xml' instead of 'text/xml'

### ISSUE THREAD

**Issue by chaitanyagpt21** [vpulim/node-soap#719]
I am doing API integration with a third party for my node application. Their APIs are written in .NET probably using SOAP 1.2 and they require content-type as 'application/soap+xml' instead of 'text/xml'. I also tested testcases for this module after changing the content-type. There are no such issues. Please look into it or if possible, we can pass parameter for the same.

**Comment by Himanshu4** [comment]
+1

**Comment by garvitlnmiit** [comment]
+1

**Comment by jsdevel** [comment]
Please open a PR with tests.
