### ISSUE TITLE
Need to override the default namespace for "xmlns:soap".

### ISSUE THREAD

**Issue by chaitanyagpt21** [vpulim/node-soap#720]
By default, the namespace "xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\" " is added to the SOAP envelope. But, I need to add a different namespace for the same in the SOAP request which is xmlns:soap="http://www.w3.org/2003/05/soap-envelope". I am passing the latter in client.wsdl.xmlnsInEnvelope but since the former one is present by default in request, I dont get any response from server. When I remove the former namespace and keep only the latter in request, I get the desired response.

**Comment by Himanshu4** [comment]
+1

**Comment by garvitlnmiit** [comment]
+1

**Comment by jsdevel** [comment]
Please open a PR.

**Comment by shashank-14612** [comment]
+1
