### ISSUE TITLE
overloaded operation names

### ISSUE THREAD

**Issue by maickelfu** [vpulim/node-soap#722]
Hi I'm working with a wsdl that uses overloaded operation names.
I didn't find any support for this kind of wsdl.
What is the best way to make this work without altering the wsdl or node-soap lib?

\<wsdl:operation name="OveloadedOperationName">
\<wsdl:input message="tns:OveloadedOperationNameDetailsSoapIn"/>
\<wsdl:output message="tns:OveloadedOperationNameDetailsSoapOut"/>
\</wsdl:operation>
\<wsdl:operation name="OveloadedOperationName">
\<wsdl:input message="tns:OveloadedOperationNameDetailsOtherSoapIn"/>
\<wsdl:output message="tns:OveloadedOperationNameDetailsOtherSoapOut"/>
\</wsdl:operation>"

**Comment by nooitaf** [comment]
+1

**Comment by jsdevel** [comment]
Not sure.  For now it sounds like modifying the WSDL is your best bet (not ideal).  Please open a PR with the enhancement.
