### ISSUE TITLE
Download latest version

### ISSUE THREAD

**Issue by lauort** [vpulim/node-soap#727]
Hi all,

I downloaded the npm package but i do not see the last changes made in the project. Do I need something special?

I used "npm install soap"

Regards

**Comment by herom** [comment]
Did you do this on a "clean" project without `npm-shrinkwrap.json`? If you did so, the installed version should resolve to `v0.9.3` and include the changes listed in our [History](https://github.com/vpulim/node-soap/blob/master/History.md).

**Comment by jsdevel** [comment]
A look at commit history for `Release x.x` should let you know what has been published.
