### ISSUE TITLE
Create list using array with multiple entries

### ISSUE THREAD

**Issue by lauort** [vpulim/node-soap#728]
Hi all,

I am trying to manage this problem. I send this json structure to the soap client:

```javascript
{
		"batters":
			{
				"batter":
					[
						{ "id": "1001", "type": "Regular" },
						{ "id": "1002", "type": "Chocolate" },
					]
			}
}
```

The problem is the code had created that request:
```xml
<batters>
<batter>
<id>1001</id>					
<value>Regular</value>
</batter>
</batters>
<batters>
<batter>
<id>1002</id>					
<value>Chocolate</value>
</batter>
</batters>
```

Why had it created two arrays for the same node??

Regards

**Comment by herom** [comment]
Perhaps [this Request/Response sample](https://github.com/vpulim/node-soap/tree/master/test/request-response-samples/addList__complex_extension_namespace_for_arrays) is of use for you?

**Comment by lauort** [comment]
Hi @herom, I found the problem and It has solved, The structure the client passed to us, it was wrong.

Regards
