### ISSUE TITLE
0.9.2 -> 0.9.3 upgrade. Namespace removed from array objects when converted to XML.

### ISSUE THREAD

**Issue by benjaminpearson** [vpulim/node-soap#738]
Hi guys, I updated from 0.9.2 to 0.9.3 and see the following lines were added to [the commit](https://github.com/vpulim/node-soap/commit/f45035082e266a442abcc43eb9905a70969fe632#diff-0e69590ba3779ce36d55f98da7266b97R1552) which appears to break our XML being constructed when making requests. I was wondering what the lines were added to solve and whether we are not sending our requests correctly? If I remove this code block then my requests work as they did previously.

```
var nameWithNsRegex = /^([^:]+):([^:]+)$/.exec(name);
if (nameWithNsRegex) {
   nonSubNameSpace = nameWithNsRegex[1] + ':';
   name = nameWithNsRegex[2];
}
```

This is the payload that we are converting to xml. Notice the `a:` namespace on the `a:Customers` parent key for the underlying array.

```
{
  wsExampleRequest: {
    'a:Complete': 'Y',
    'a:Customers': [
      { 
        'a:Customer': { 
          'a:DOB': '01/01/1990',       
          'a:FirstName': 'Tim',
          'a:LastName': 'Pope',
        }
      }
    ],
    'a:Email': 'test@example.com',
  }
}
```

Then when converted to XML the `a:` prefix is removed from that `<Customers></Customers>` parent key.

```
<soap:Envelope xmlns:a="http://schemas.datacontract.org/......." xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soap:Body>
    <Example xmlns="http://tempuri.org/">
      <wsExampleRequest>
        <a:Complete>Y</a:Complete>
        <Customers>
          <a:Customer>
            <a:DOB>01/01/1990</a:DOB>            
            <a:FirstName>Tim</a:FirstName>            
            <a:LastName>Pope</a:LastName>
          </a:Customer>
        </Customers>
        <a:Email>test@example.com</a:Email>
      </wsExampleRequest>
    </Example>
  </soap:Body>
</soap:Envelope>
```

I tried to see if there was other people with this same issue and couldn't see it raised, although I might have missed it. 
Anyway thought I'd just raise it as a question.

**Comment by jsdevel** [comment]
@benjaminpearson can you open a PR to fix this?

**Comment by benjaminpearson** [comment]
@jsdevel Yep sure thing, the PR though would just be a commit removing that code block because I don't really understand why it was added? I'm guessing there was a reason it was added though...

**Comment by herom** [comment]
The commit which introduced this behaviour was [Allowing namespace overriding for elements](https://github.com/vpulim/node-soap/commit/f45035082e266a442abcc43eb9905a70969fe632) - the README was also updated, perhaps this will help you a bit with that @benjaminpearson ?

**Comment by jsdevel** [comment]
Looks like the fix didn't handle array elements :smirk:
