### ISSUE TITLE
XSD Circular/Cyclic Reference

### ISSUE THREAD

**Issue by chayoka** [vpulim/node-soap#743]
Hi,

I'm dealing with WSDL with circular/cyclic reference, e.g. like below

    file.wsdl
        xs:import namespace="A" schemaLocation: A.xsd
    A.xsd
        xs:import namespace="B" schemaLocation: B.xsd
    B.xsd
        xs:import namespace="A" schemaLocation: A.xsd

I noticed the lib/wsdl.js will perform infinite loop when hitting circular reference.
Any suggestion or thought?

**Comment by jsdevel** [comment]
I too have noticed this behavior, and would lean toward classifying it as a valid bug.  The specs do not define circular references as being an error [see w3.org/xsd](http://www.w3.org/TR/xmlschema11-1/#composition-schemaImport).

**Comment by frikkievb** [comment]
I am having the same issue.

**Comment by fabiancook** [comment]
I came across this today, tried various ways to get around it, the only way to do this was to check to see if the "parent" was loading, aka, has it loaded previously, returning it here worked fine

I suggest we should have an private method that can be called internal to the WSDL, which can then do this logic?

```
var loading = { };

function open_wsdl(uri, options, callback) {
  var parent;

  if (typeof options === 'function') {
    callback = options;
    options = {};
  }

  if ( parent = loading[ uri ] ) {
    return callback.call( parent, null, parent )
  }

  // .....
}
```

Thoughs?
