### ISSUE TITLE
Possible Array serialization issue

### ISSUE THREAD

**Issue by theanimal666** [vpulim/node-soap#748]
Hallo,

First of all thanks for this great library.

I'm working on an API and having troubles because of the way arrays get serialized into the request body.

My input object looks like:

```
{
options:
  [{
   option: {
      optionName: 'optname1',
      optionValue: 'value1'
    }
   },{
    option: {
      optionName: 'optname2',
      optionValue: 'value2'
    }
 }]
}
```
it gets serialized to:
```
<options>
   <option>
       <optionName>optname1</optionName>
       <optionValue>value1</optionValue>
   </option>
</options>
<options>
   <option>
       <optionName>optname2</optionName>
       <optionValue>value2</optionValue>
   </option>
</options>
```

while the server expects it to be formatted as:
```
<options>
   <option>
       <optionName>optname1</optionName>
       <optionValue>value1</optionValue>
   </option>
   <option>
       <optionName>optname2</optionName>
       <optionValue>value2</optionValue>
   </option>
</options>
```

I found the responsible code (llib/wsdl.js l: 1528..) and implemented a fix in my local fork but this causes several tests to fail.
I'm not really deep into this SOAP/XML stuff an therefore i'm not sure if that is a issue of the library or just bug in the servers SOAP server implementation.

thanks in advance for you help,
kind regards

**Comment by jsdevel** [comment]
please open a PR
