### ISSUE TITLE
Add namespaces to soap envelope?

### ISSUE THREAD

**Issue by stephengardner** [vpulim/node-soap#759]
Is there a way to either change a namespace prefix or add additional namespaces?  I seem to be able to add it as an "attribute" item from within my Javascript object, but if I want to add it to `soap:Body` I'm not sure how.  I'm having an issue with this.  I saw a couple issues about it but nothing seemed to solve this.

**Comment by stephengardner** [comment]
To make this more clear, I need to give a `"xmlns:_something_"` prefix to the actual endpoint node (in this case the node is called `Import_User`).  
So I need it to end up like : `<m:Import_User xmlns:m="...">
<m:UserName>Something</m:UserName>
<SomeOtherNodeWithoutPrefix>SomethingElse</SomeOtherNodeWithoutPrefix`

How can I do this?

**Comment by jsdevel** [comment]
```
{
   'prefix:element': value
}
```

**Comment by jsdevel** [comment]
Try with `0.10.0` as well.

**Comment by stephengardner** [comment]
That doesn't seem to work.  If `Import_User` is the endpoint, `<soap:Body>` is automatically populated with a `<Import_User>` node.  
```
{
   'prefix:element' : value
}
```
only adds elements within that node, correct?

Doing it this way just created an `m:Import_User` node within my `Import_User` node

**Comment by ChopperLee2011** [comment]
i also have this issue, do not find an api to add prefix namespace to the `method`.
