### ISSUE TITLE
Howto get request body?

### ISSUE THREAD

**Issue by alverdal** [vpulim/node-soap#762]
Is it possible to retrieve the request body in "raw" format and not in Json on server side?

In the http module I can retrieve the body from the request by event "data" as written below:

But when I try to retrive the data when the soap-module is wrapping up the http-server there is no "data" event...

request.on('data', function (chunk) {
        console.log("Received body data:");
        console.log(chunk.toString());

        fs.writeFile("temp/lastCallBodyContent.txt", chunk.toString(), function (err) {

            if (err) {
                return console.log(err);
            }
            
            console.log("File was written to disk");

            }

        );

**Comment by herom** [comment]
Sure, just add an `eventListener` to the client's `request` event - this should give you the raw XML data which is going to be sent. Sadly, we don't have the several events documented yet - this would make an excellent PR if you're willing to contribute :smiley: :+1:

**Comment by alverdal** [comment]
But I would like to see the raw-XML data on the server side, not on the client side.
on http-module you can add eventListener on request object like: 

request.on('data', function (chunk) {
console.log("Received body data:");
console.log(chunk.toString());
}

But this doesn't work when soap-module is wrapping up the http server:
var server = http.createServer(function (request, response) {

request.on('data', function (chunk) {
console.log("Received body data:");
console.log(chunk.toString());
}

        response.end("404: Not Found: " + request.url)
    });


server = soap.listen(server, '/testservice', myService, xml);
